// Universal schema — cases (core litigation entity).
export const CasesSchema = {
  collection: 'cases',
  label: 'Cases',
  primaryKey: 'id',
  core: true,
  fields: {
    id: 'string',
    caseNumber: 'string',
    title: 'string',
    case_type: 'string',
    case_number: 'number',
    case_year: 'number',
    case_display_number: 'string',
    plaintiff: 'string',
    defendant: 'string',
    court: 'string',
    courtName: 'string',
    judge: 'string',
    stage: 'string',
    parties: 'object',
    description: 'string',
    nextHearing: 'datetime',
    filingDate: 'string',
    wsFilingDate: 'string',
    advocate: 'string',
    client: 'string',
    status: 'string',
    tags: 'array',
    archived: 'boolean',
    watch: 'boolean',
    stageHistory: 'array',
    createdAt: 'datetime',
    updatedAt: 'datetime',
  },
  required: ['caseNumber', 'title', 'case_type', 'case_number', 'case_year'],
  defaults: {
    status: 'Active',
    tags: [],
    archived: false,
    watch: false,
    stageHistory: [],
  },
  relations: [],
  indexes: ['caseNumber', 'case_display_number', 'case_type', 'status', 'stage', 'archived'],
};

export default CasesSchema;
