// Universal schema — cases (core litigation entity).
export const CasesSchema = {
  collection: 'cases',
  label: 'Cases',
  primaryKey: 'id',
  core: true,
  fields: {
    id: 'string',
    case_number_str: 'string',
    title: 'string',
    case_type: 'string',
    case_number: 'number',
    case_year: 'number',
    case_display_number: 'string',
    plaintiff: 'string',
    defendant: 'string',
    court: 'string',
    court_name: 'string',
    judge: 'string',
    stage: 'string',
    parties: 'object',
    description: 'string',
    next_hearing: 'datetime',
    filing_date: 'string',
    ws_filing_date: 'string',
    advocate: 'string',
    client: 'string',
    status: 'string',
    tags: 'array',
    archived: 'boolean',
    watch: 'boolean',
    stage_history: 'array',
    created_at: 'datetime',
    updated_at: 'datetime',
  },
  required: ['case_number_str', 'title', 'case_type', 'case_number', 'case_year'],
  defaults: {
    status: 'Active',
    tags: [],
    archived: false,
    watch: false,
    stage_history: [],
  },
  relations: [],
  indexes: ['case_number_str', 'case_display_number', 'case_type', 'status', 'stage', 'archived'],
};

export default CasesSchema;
