export const ChangelogReleasesSchema = {
  collection: 'changelog_releases',
  label: 'Changelog Releases',
  primaryKey: 'id',
  core: true,
  fields: {
    id: 'string',
    version: 'string',
    release_date: 'datetime',
    release_time: 'string',
    timezone: 'string',
    build_number: 'string',
    release_type: 'string',
    title: 'string',
    description: 'string',
    summary: 'string',
    status: 'string',
    author: 'string',
    environment: 'string',
    related_issue: 'string',
    git_commit_hash: 'string',
    created_at: 'datetime',
    created_by: 'string',
    updated_at: 'datetime',
    updated_by: 'string',
  },
  required: ['version', 'release_type', 'title', 'status', 'author'],
  defaults: {
    status: 'planned',
    environment: 'production',
    timezone: Intl.DateTimeFormat().resolvedOptions().timeZone,
    release_date: null,
    release_time: null,
  },
  relations: [],
  indexes: ['version', 'release_type', 'status', 'release_date'],
};

export default ChangelogReleasesSchema;
