// Universal schema — judgments (local citation corpus; never fabricated).
export const JudgmentsSchema = {
  collection: 'judgments',
  label: 'Judgments',
  primaryKey: 'id',
  core: false,
  fields: {
    id: 'string',
    citation: 'string',
    neutralCitation: 'string',
    reporterCitation: 'string',
    court: 'string',
    bench: 'string',
    judges: 'array',
    caseNumber: 'string',
    caseType: 'string',
    jurisdiction: 'string',
    stage: 'string',
    source: 'string',
    status: 'string',
    plaintiff: 'string',
    defendant: 'string',
    typeOfProceeding: 'string',
    natureOfDispute: 'string',
    act: 'string',
    plaintiffType: 'string',
    defendantType: 'string',
    plaintiffCounsel: 'string',
    defendantCounsel: 'string',
    authorityLevel: 'string',
    jurisdictionalScope: 'string',
    precedentialValue: 'string',
    reviewStatus: 'string',
    headnotes: 'string',
    practiceArea: 'string',
    category: 'string',
    provisions: 'array',
    legalIssue: 'array',
    tags: 'array',
    judgmentType: 'string',
    overruledBy: 'string',
    followedBy: 'string',
    title: 'string',
    summary: 'string',
    fullText: 'string',
    date: 'datetime',
    judgmentDate: 'datetime',
    pronouncementDate: 'datetime',
    uploadDate: 'datetime',
    createdAt: 'datetime',
    updatedAt: 'datetime',
    createdBy: 'string',
    modifiedBy: 'string',
    versionHistory: 'array',
    changeLog: 'array',
    keywords: 'array',
    casesCited: 'array',
    acts: 'array',
    paragraphs: 'array',
    sourceUrl: 'string',
    ratioDecidendi: 'string',
    obiterDicta: 'string',
    keyFindings: 'string',
    notes: 'string',
    researchNotes: 'string',
    reviewComments: 'string',
    applicableStages: 'array',
    legalPrinciple: 'string',
    usageNotes: 'string',
    documents: 'array',
    annexures: 'array',
    supportingDocuments: 'array',
    externalReferences: 'array',
    favourite: 'boolean',
    pinned: 'boolean',
    finalDecision: 'string',
  },
  required: ['citation'],
  defaults: { keywords: [], acts: [], paragraphs: [], provisions: [], legalIssue: [], tags: [], judges: [], casesCited: [], applicableStages: [], documents: [], annexures: [], supportingDocuments: [], externalReferences: [] },
  relations: [],
  indexes: ['court', 'caseType', 'jurisdiction'],
};

export default JudgmentsSchema;
