import { listSchemas, getSchema, SCHEMA_VERSION } from './index.js';

const PG = { string: 'text', number: 'numeric', boolean: 'boolean', datetime: 'timestamptz', array: 'jsonb', object: 'jsonb', json: 'jsonb' };
const MONGOOSE = { string: 'String', number: 'Number', boolean: 'Boolean', datetime: 'Date', array: 'Array', object: 'Object', json: 'Object' };
const BSON = { string: 'string', number: 'number', boolean: 'bool', datetime: 'date', array: 'array', object: 'object', json: 'object' };
const FS = { string: 'string', number: 'number', boolean: 'bool', datetime: 'timestamp', array: 'list', object: 'map', json: 'map' };

const q = (id) => `"${id}"`;

function toSupabase(schema) {
  const cols = Object.entries(schema.fields).map(([name, type]) => {
    if (name === schema.primaryKey) return `  ${q(name)} text primary key`;
    return `  ${q(name)} ${PG[type] || 'text'}`;
  });
  const createTable = `create table if not exists ${q(schema.collection)} (\n${cols.join(',\n')}\n);`;
  const createIndexes = (schema.indexes || []).map(
    (f) => `create index if not exists ${`idx_${schema.collection}_${f}`} on ${q(schema.collection)} (${q(f)});`
  );
  const alterTable = (existingColumns = []) =>
    Object.entries(schema.fields)
      .filter(([name]) => !existingColumns.includes(name))
      .map(([name, type]) => `alter table ${q(schema.collection)} add column if not exists ${q(name)} ${name === schema.primaryKey ? 'text' : (PG[type] || 'text')};`);
  return { provider: 'supabase', collection: schema.collection, createTable, createIndexes, alterTable, sql: [createTable, ...createIndexes].join('\n') };
}

function toFirebase(schema) {
  const checks = Object.entries(schema.fields)
    .filter(([name]) => name !== schema.primaryKey)
    .map(([name, type]) => {
      const t = FS[type] || 'string';
      const present = `(!('${name}' in request.resource.data) || request.resource.data.${name} == null || request.resource.data.${name} is ${t})`;
      return `        ${present}`;
    });
  const required = (schema.required || []).map((f) => `        '${f}' in request.resource.data`);
  const rule = [
    `    match /${schema.collection}/{docId} {`,
    '      allow read: if true;',
    '      allow write: if',
    [...required, ...checks].join(' &&\n') || '        true',
    '      ;',
    '    }',
  ].join('\n');
  const indexes = (schema.indexes || []).map((f) => ({
    collectionGroup: schema.collection,
    queryScope: 'COLLECTION',
    fields: [{ fieldPath: f, order: 'ASCENDING' }],
  }));
  return {
    provider: 'firebase',
    collection: schema.collection,
    definition: { collection: schema.collection, fields: schema.fields, required: schema.required || [] },
    rules: rule,
    indexes,
  };
}

function toMongo(schema) {
  const defLines = Object.entries(schema.fields).map(([name, type]) => {
    const mt = MONGOOSE[type] || 'String';
    const idx = (schema.indexes || []).includes(name) ? ', index: true' : '';
    const uniq = name === schema.primaryKey ? ', unique: true' : '';
    return `  ${name}: { type: ${mt}${idx}${uniq} }`;
  });
  const mongooseDefinition =
    `// generated by SchemaCompiler — collection: ${schema.collection}\n` +
    `const ${schema.collection}Schema = new mongoose.Schema({\n${defLines.join(',\n')}\n}, { collection: '${schema.collection}', strict: false });`;

  const properties = {};
  Object.entries(schema.fields).forEach(([name, type]) => { properties[name] = { bsonType: BSON[type] || 'string' }; });
  const jsonSchema = {
    $jsonSchema: {
      bsonType: 'object',
      required: schema.required || [],
      properties,
    },
  };
  const indexes = [
    { key: { [schema.primaryKey]: 1 }, name: `${schema.primaryKey}_unique`, unique: true },
    ...(schema.indexes || []).map((f) => ({ key: { [f]: 1 }, name: `${f}_idx` })),
  ];
  return { provider: 'mongodb', collection: schema.collection, mongooseDefinition, jsonSchema, indexes };
}

function toLocal(schema) {
  return {
    provider: 'local',
    collection: schema.collection,
    init: { collection: schema.collection, fields: Object.keys(schema.fields), defaults: schema.defaults || {} },
  };
}

// P5: Supabase compatibility — resolves auth.uid() to application role via users.roleCode
function systemSqlSupabaseAuth() {
  return [
    '-- ============================================================',
    '-- 5a. SUPABASE AUTH COMPATIBILITY (P5)',
    '-- ============================================================',
    '-- Maps auth.uid() → users.roleCode for RLS policies without relying on',
    '-- browser users becoming PostgreSQL roles directly.',
    '--',
    '-- Usage in RLS policies:',
    '--   USING (current_user_role() = ANY(ARRAY[\'admin\', \'manager\']))',
    '--',
    '-- Falls back to \'anon\' when the calling user is not authenticated',
    '-- (auth.uid() IS NULL) or when the users table is not yet accessible.',
    '',
    'create or replace function current_user_role()',
    'returns text',
    'language plpgsql',
    'security definer',
    'stable',
    'as $$',
    'declare',
    '  v_role text;',
    'begin',
    '  -- When called outside Supabase auth context, use PostgreSQL current_role',
    '  if current_setting(\'role\', true) = \'lexai_admin\' then return \'admin\'; end if;',
    '  -- Try Supabase auth.uid()',
    '  begin',
    '    if auth.uid() is null then',
    '      -- Not authenticated via Supabase — check pg role',
    '      if current_user = \'anon\' then return \'anon\'; end if;',
    '      if current_user = \'service_role\' then return \'admin\'; end if;',
    '      return \'anon\';',
    '    end if;',
    '    -- Authenticated: look up application role from users table',
    '    select role_code into strict v_role from users where id = auth.uid()::text;',
    '    return v_role;',
    '  exception',
    '    when others then',
    '      -- If users table not accessible, fall back to role name',
    '      if current_user = \'authenticated\' then return \'user\'; end if;',
    '      return \'anon\';',
    '  end;',
    'end;',
    '$$;',
  ].join('\n');
}

// ---- System infrastructure SQL sections (emitted in dependency order) -----
// P1: migration_registry created FIRST so exec_sql/safe_ddl can audit into it
// P4: FK creation extracted to separate method, called AFTER all tables exist

function systemSqlRoles() {
  return [
    '-- ============================================================',
    '-- 1. ROLE-BASED ACCESS CONTROL',
    '-- ============================================================',
    '',
    'do $$ begin',
    "  if not exists (select from pg_roles where rolname = 'lexai_admin') then",
    '    create role lexai_admin;',
    '  end if;',
    "  if not exists (select from pg_roles where rolname = 'lexai_manager') then",
    '    create role lexai_manager;',
    '  end if;',
    "  if not exists (select from pg_roles where rolname = 'lexai_user') then",
    '    create role lexai_user;',
    '  end if;',
    'end $$;',
  ].join('\n');
}

function systemSqlMigrationRegistry() {
  return [
    '-- ============================================================',
    '-- 2. migration_registry — audit log of all schema migrations',
    '-- Created FIRST so exec_sql/safe_ddl can write audit entries.',
    '-- ============================================================',
    'create table if not exists migration_registry (',
    '  id text primary key default gen_random_uuid()::text,',
    '  version integer not null,',
    '  description text,',
    '  sql_hash text,',
    '  applied_at timestamptz default now(),',
    '  duration_ms integer default 0,',
    '  success boolean default true,',
    '  error text,',
    "  action text default 'migrate'",
    ');',
    '',
    "create index if not exists idx_migration_registry_version on migration_registry (version);",
    "create index if not exists idx_migration_registry_applied_at on migration_registry (applied_at);",
  ].join('\n');
}

function systemSqlExecSql() {
  return [
    '-- ============================================================',
    '-- 3. exec_sql — hardened DDL execution (ADMIN ONLY)',
    '-- ============================================================',
    '-- Audits every action via migration_registry (must exist before calling).',
    '-- Uses IF EXISTS guard on INSERT so it works even if registry is absent.',
    '',
    'create or replace function exec_sql(sql text)',
    'returns void',
    'language plpgsql',
    'security definer',
    'as $$',
    'begin',
    '  if exists (select 1 from pg_tables where tablename = \'migration_registry\') then',
    "    insert into migration_registry (id, version, description, sql_hash, applied_at, duration_ms, success)",
    "    values (gen_random_uuid()::text, 0, 'exec_sql', md5(sql), now(), 0, true);",
    '  end if;',
    '  execute sql;',
    'end;',
    '$$;',
  ].join('\n');
}

// P2: All regex patterns use correct \\s for whitespace in PostgreSQL regex
function systemSqlSafeDdl() {
  return [
    '-- ============================================================',
    '-- 4. safe_ddl — allowlisted DDL execution for lexai_manager',
    '-- ============================================================',
    '-- Blocklist: DROP, TRUNCATE, ALTER TABLE DROP, GRANT/REVOKE, DML,',
    '--            CREATE DATABASE/SCHEMA/ROLE/USER/EXTENSION,',
    '--            ALTER DATABASE/SCHEMA/ROLE/USER, REINDEX, CLUSTER, VACUUM, ANALYZE',
    '-- Allowlist: CREATE TABLE IF NOT EXISTS, CREATE INDEX IF NOT EXISTS,',
    '--            ALTER TABLE ADD COLUMN IF NOT EXISTS, ALTER TABLE ADD CONSTRAINT,',
    '--            CREATE OR REPLACE FUNCTION, ALTER TABLE IF EXISTS,',
    '--            ALTER TABLE ... ENABLE/DISABLE ROW LEVEL SECURITY,',
    '--            CREATE/ALTER/DROP POLICY, COMMENT ON, DO $$ blocks',
    '-- P2: All \\s patterns correctly escaped for PostgreSQL POSIX regex.',
    '-- Uses IF EXISTS guard on migration_registry INSERT.',
    '',
    'create or replace function safe_ddl(sql text)',
    'returns void',
    'language plpgsql',
    'security definer',
    'as $$',
    'declare',
    '  v_upper text;',
    'begin',
    '  v_upper := upper(sql);',
    '',
    '  -- Blocklist (checked before allowlist)',
    "  if v_upper ~ '^\\s*DROP\\s+(DATABASE|SCHEMA|TABLE|VIEW|FUNCTION|INDEX|ROLE|POLICY|TRIGGER|EXTENSION|PUBLICATION|SUBSCRIPTION)' then",
    "    raise exception 'safe_ddl: DROP is not permitted';",
    '  end if;',
    "  if v_upper ~ '^\\s*TRUNCATE' then",
    "    raise exception 'safe_ddl: TRUNCATE is not permitted';",
    '  end if;',
    "  if v_upper ~ 'ALTER\\s+TABLE.*DROP\\s+(COLUMN|CONSTRAINT)' then",
    "    raise exception 'safe_ddl: ALTER TABLE DROP is not permitted';",
    '  end if;',
    "  if v_upper ~ '^\\s*(GRANT|REVOKE)' then",
    "    raise exception 'safe_ddl: GRANT/REVOKE is not permitted';",
    '  end if;',
    "  if v_upper ~ '^\\s*(DELETE|UPDATE|INSERT|TRUNCATE)\\s' then",
    "    raise exception 'safe_ddl: DML statements are not permitted; use CRUD APIs';",
    '  end if;',
    "  if v_upper ~ '^\\s*CREATE\\s+(DATABASE|SCHEMA|ROLE|USER|EXTENSION)\\s' then",
    "    raise exception 'safe_ddl: CREATE DATABASE/SCHEMA/ROLE/USER/EXTENSION is not permitted';",
    '  end if;',
    "  if v_upper ~ '^\\s*ALTER\\s+(DATABASE|SCHEMA|ROLE|USER)\\s' then",
    "    raise exception 'safe_ddl: ALTER DATABASE/SCHEMA/ROLE/USER is not permitted';",
    '  end if;',
    '',
    '  -- Allowlist',
    '  if not (',
    "    v_upper ~ '^\\s*CREATE\\s+TABLE\\s+IF\\s+NOT\\s+EXISTS\\s' or",
    "    v_upper ~ '^\\s*CREATE\\s+INDEX\\s+IF\\s+NOT\\s+EXISTS\\s' or",
    "    v_upper ~ 'ALTER\\s+TABLE.*ADD\\s+COLUMN\\s+IF\\s+NOT\\s+EXISTS' or",
    "    v_upper ~ 'ALTER\\s+TABLE.*ADD\\s+CONSTRAINT' or",
    "    v_upper ~ '^\\s*CREATE\\s+OR\\s+REPLACE\\s+FUNCTION\\s' or",
    "    v_upper ~ '^\\s*ALTER\\s+TABLE\\s+IF\\s+EXISTS\\s' or",
    "    v_upper ~ 'ALTER\\s+TABLE.*ENABLE\\s+ROW\\s+LEVEL\\s+SECURITY' or",
    "    v_upper ~ 'ALTER\\s+TABLE.*DISABLE\\s+ROW\\s+LEVEL\\s+SECURITY' or",
    "    v_upper ~ '^\\s*CREATE\\s+POLICY\\s' or",
    "    v_upper ~ '^\\s*ALTER\\s+POLICY\\s' or",
    "    v_upper ~ '^\\s*DROP\\s+POLICY\\s+IF\\s+EXISTS\\s' or",
    "    v_upper ~ '^\\s*COMMENT\\s+ON\\s' or",
    "    v_upper ~ '^\\s*DO\\s+\\$\\$' or",
    "    v_upper ~ '^\\s*--'",
    '  ) then',
    "    raise exception 'safe_ddl: Statement does not match any allowed pattern: %', substr(sql, 1, 80);",
    '  end if;',
    '',
    '  -- Audit (with IF EXISTS guard so migration_registry need not exist yet)',
    '  if exists (select 1 from pg_tables where tablename = \'migration_registry\') then',
    "    insert into migration_registry (id, version, description, sql_hash, applied_at, duration_ms, success)",
    "    values (gen_random_uuid()::text, 0, 'safe_ddl', md5(sql), now(), 0, true);",
    '  end if;',
    '  execute sql;',
    'end;',
    '$$;',
    '',
    'grant execute on function exec_sql(text) to lexai_admin;',
    'grant execute on function safe_ddl(text) to lexai_manager;',
  ].join('\n');
}

function systemSqlSafeCreateFk() {
  return [
    '-- ============================================================',
    '-- 5. SAFE FOREIGN KEY HELPER',
    '-- ============================================================',
    '-- safe_create_fk — creates a foreign key only if the referenced table,',
    '-- referenced column, and source column all exist and the FK does not',
    '-- already exist. Never fails on missing references.',
    '',
    'create or replace function safe_create_fk(',
    '  p_source_table text,',
    '  p_source_column text,',
    '  p_target_table text,',
    '  p_target_column text,',
    '  p_constraint_name text,',
    "  p_on_delete text default 'CASCADE'",
    ') returns void',
    'language plpgsql',
    'as $safe_fk$',
    'declare',
    '  v_exists boolean;',
    'begin',
    '  select exists (',
    '    select 1 from pg_constraint c',
    '    join pg_class t on t.oid = c.conrelid',
    '    where t.relname = p_source_table',
    '    and c.conname = p_constraint_name',
    '  ) into v_exists;',
    '  if v_exists then return; end if;',
    '  if not exists (select 1 from pg_class where relname = p_source_table) then return; end if;',
    '  if not exists (select 1 from pg_class where relname = p_target_table) then return; end if;',
    '  if not exists (',
    '    select 1 from pg_attribute a',
    '    join pg_class t on t.oid = a.attrelid',
    '    where t.relname = p_source_table',
    '    and a.attname = p_source_column',
    '    and a.attnum > 0',
    '  ) then return; end if;',
    '  if not exists (',
    '    select 1 from pg_attribute a',
    '    join pg_class t on t.oid = a.attrelid',
    '    where t.relname = p_target_table',
    '    and a.attname = p_target_column',
    '    and a.attnum > 0',
    '  ) then return; end if;',
    '  execute format($fmt$',
    '    alter table %I add constraint %I',
    '    foreign key (%I) references %I (%I) on delete %s',
    '  $fmt$, p_source_table, p_constraint_name, p_source_column, p_target_table, p_target_column, upper(p_on_delete));',
    'end;',
    '$safe_fk$;',
  ].join('\n');
}

// P4: FK creation calls extracted — emitted AFTER all application tables exist
function systemSqlForeignKeys() {
  return [
    '-- ============================================================',
    '-- 6. FOREIGN KEY INSTALLATION (P4 — after all tables exist)',
    '-- ============================================================',
    '-- All safe_create_fk calls run after registry tables AND application',
    '-- tables are created, so referenced tables/columns are guaranteed to exist.',
    "select safe_create_fk('reminders', 'caseId', 'cases', 'id', 'fk_reminders_case_id', 'CASCADE');",
    "select safe_create_fk('notes', 'caseId', 'cases', 'id', 'fk_notes_case_id', 'CASCADE');",
    "select safe_create_fk('hearings', 'caseId', 'cases', 'id', 'fk_hearings_case_id', 'CASCADE');",
    "select safe_create_fk('drafts', 'caseId', 'cases', 'id', 'fk_drafts_case_id', 'CASCADE');",
    "select safe_create_fk('documents', 'caseId', 'cases', 'id', 'fk_documents_case_id', 'CASCADE');",
    "select safe_create_fk('caseHistory', 'caseId', 'cases', 'id', 'fk_case_history_case_id', 'CASCADE');",
    "select safe_create_fk('caseFolders', 'caseId', 'cases', 'id', 'fk_case_folders_case_id', 'CASCADE');",
    "select safe_create_fk('caseActivity', 'caseId', 'cases', 'id', 'fk_case_activity_case_id', 'CASCADE');",
    "select safe_create_fk('auditLogs', 'userId', 'users', 'id', 'fk_audit_logs_user_id', 'SET NULL');",
    "select safe_create_fk('users', 'roleCode', 'roles', 'code', 'fk_users_role_code', 'RESTRICT');",
    "select safe_create_fk('caseFolders', 'parentId', 'caseFolders', 'id', 'fk_case_folders_parent_id', 'CASCADE');",
  ].join('\n');
}

function systemSqlRegistryTables() {
  return [
    '-- ============================================================',
    '-- 7. REGISTRY TABLES',
    '-- ============================================================',
    '',
    '-- schema_registry — tracks schema versions & migrations applied',
    'create table if not exists schema_registry (',
    '  id text primary key default gen_random_uuid()::text,',
    '  version integer not null default 0,',
    '  description text,',
    '  checksum text,',
    "  applied_at timestamptz default now(),",
    "  applied_by text default current_user",
    ');',
    '',
    '-- entity_registry — registered entity definitions',
    'create table if not exists entity_registry (',
    '  id text primary key default gen_random_uuid()::text,',
    '  name text not null unique,',
    '  label text,',
    '  table_name text not null,',
    "  primary_key text default 'id',",
    '  core boolean default false,',
    "  fields jsonb default '{}'::jsonb,",
    "  indexes jsonb default '{}'::jsonb,",
    "  created_at timestamptz default now(),",
    "  updated_at timestamptz default now()",
    ');',
    '',
    '-- field_registry — field-level metadata per entity',
    'create table if not exists field_registry (',
    '  id text primary key default gen_random_uuid()::text,',
    '  entity text not null,',
    '  field_name text not null,',
    '  field_type text not null,',
    '  required boolean default false,',
    '  unique_field boolean default false,',
    '  default_value text,',
    "  created_at timestamptz default now()",
    ');',
    '',
    '-- provider_registry — database provider configuration',
    'create table if not exists provider_registry (',
    '  id text primary key default gen_random_uuid()::text,',
    '  provider_type text not null,',
    '  label text,',
    "  config jsonb default '{}'::jsonb,",
    '  active boolean default true,',
    '  connected_at timestamptz,',
    "  created_at timestamptz default now(),",
    "  updated_at timestamptz default now()",
    ');',
    '',
    '-- installer_state — instantaneous installation tracking',
    'create table if not exists installer_state (',
    "  id text primary key default 'default',",
    "  install_status text not null default 'none' check (install_status in ('none', 'in_progress', 'completed', 'failed')),",
    '  schema_version integer not null default 0,',
    '  installer_version integer not null default 1,',
    '  provider text,',
    '  database_type text,',
    '  verified_at timestamptz,',
    '  installed_at timestamptz,',
    "  updated_at timestamptz default now()",
    ');',
  ].join('\n');
}

function systemSqlMappingTables() {
  return [
    '-- ============================================================',
    '-- 8. SCHEMA MAPPING TABLES',
    '-- ============================================================',
    '',
    '-- schema_mapping — LexAI entity name ↔ provider table name',
    'create table if not exists schema_mapping (',
    '  id text primary key default gen_random_uuid()::text,',
    '  entity_name text not null unique,',
    '  provider_table text not null,',
    '  description text,',
    '  active boolean default true,',
    '  version integer not null default 1,',
    "  created_at timestamptz default now(),",
    "  updated_at timestamptz default now()",
    ');',
    '',
    '-- mapping_history — audit log of mapping changes',
    'create table if not exists mapping_history (',
    '  id text primary key default gen_random_uuid()::text,',
    '  entity_name text not null,',
    '  old_table text,',
    '  new_table text not null,',
    '  changed_by text,',
    '  change_reason text,',
    "  created_at timestamptz default now()",
    ');',
    '',
    '-- mapping_versions — versioned snapshots of the entire mapping set',
    'create table if not exists mapping_versions (',
    '  id text primary key default gen_random_uuid()::text,',
    '  version integer not null,',
    '  snapshot jsonb not null,',
    '  description text,',
    "  created_at timestamptz default now()",
    ');',
    '',
    '-- provider_capabilities — feature detection per provider',
    'create table if not exists provider_capabilities (',
    '  id text primary key default gen_random_uuid()::text,',
    '  provider text not null,',
    '  feature text not null,',
    '  supported boolean not null default false,',
    "  metadata jsonb default '{}'::jsonb,",
    "  detected_at timestamptz default now()",
    ');',
  ].join('\n');
}

function systemSqlProviderTables() {
  return [
    '-- ============================================================',
    '-- 9. PROVIDER ADAPTER + ENTITY PREFIX TABLES',
    '-- ============================================================',
    '',
    '-- provider_adapter_registry — dynamic adapter loading',
    'create table if not exists provider_adapter_registry (',
    '  id text primary key default gen_random_uuid()::text,',
    '  provider text not null unique,',
    '  adapter_name text not null,',
    "  adapter_version text not null default '1.0.0',",
    "  migration_engine text default 'sql',",
    "  capabilities jsonb default '{}'::jsonb,",
    '  active boolean default true,',
    "  config jsonb default '{}'::jsonb,",
    "  created_at timestamptz default now(),",
    "  updated_at timestamptz default now()",
    ');',
    '',
    '-- entity_prefix_registry — LX-ID prefix management',
    'create table if not exists entity_prefix_registry (',
    '  entity text primary key,',
    '  prefix text not null,',
    '  label text,',
    '  padding integer not null default 5,',
    '  current_sequence integer not null default 0,',
    "  created_at timestamptz default now(),",
    "  updated_at timestamptz default now()",
    ');',
    '',
    '-- id_registry — backward-compatible ID tracking',
    'create table if not exists id_registry (',
    '  entity text primary key,',
    '  prefix text not null,',
    '  sequence integer not null default 0,',
    "  created_at timestamptz default now(),",
    "  updated_at timestamptz default now()",
    ');',
    '',
    '-- foreign_key_registry — tracks FK relationships across entities',
    'create table if not exists foreign_key_registry (',
    '  id text primary key default gen_random_uuid()::text,',
    '  from_entity text not null,',
    '  from_field text not null,',
    '  to_entity text not null,',
    "  to_field text not null default 'id',",
    '  cascade_delete boolean default false,',
    '  enabled boolean default true,',
    "  created_at timestamptz default now()",
    ');',
  ].join('\n');
}

function systemSqlIdEngine() {
  return [
    '-- ============================================================',
    '-- 10. LX-ID SEQUENCE MANAGER',
    '-- ============================================================',
    '-- Generates LX-{PREFIX}-{SEQUENCE} using the entity_prefix_registry',
    '',
    'create or replace function next_lx_id(p_entity text)',
    'returns text',
    'language plpgsql',
    'as $$',
    'declare',
    '  v_prefix text;',
    '  v_pad int;',
    '  v_seq int;',
    '  v_id text;',
    'begin',
    "  insert into entity_prefix_registry (entity, prefix, label, padding, current_sequence)",
    "  values (p_entity, upper(substr(p_entity, 1, 5)), p_entity, 5, 0)",
    '  on conflict (entity) do nothing;',
    '  select prefix, padding into strict v_prefix, v_pad from entity_prefix_registry where entity = p_entity;',
    '  update entity_prefix_registry',
    '  set current_sequence = current_sequence + 1,',
    '      updated_at = now()',
    '  where entity = p_entity',
    '  returning current_sequence into v_seq;',
    "  v_id := 'LX-' || v_prefix || '-' || lpad(v_seq::text, v_pad, '0');",
    '  return v_id;',
    'end;',
    '$$;',
  ].join('\n');
}

function systemSqlRls() {
  return [
    '-- ============================================================',
    '-- 11. ROW LEVEL SECURITY',
    '-- ============================================================',
    '-- Enable RLS on all registry tables',
    'alter table if exists schema_registry enable row level security;',
    'alter table if exists entity_registry enable row level security;',
    'alter table if exists field_registry enable row level security;',
    'alter table if exists provider_registry enable row level security;',
    'alter table if exists migration_registry enable row level security;',
    'alter table if exists installer_state enable row level security;',
    'alter table if exists provider_adapter_registry enable row level security;',
    'alter table if exists schema_mapping enable row level security;',
    'alter table if exists mapping_history enable row level security;',
    'alter table if exists mapping_versions enable row level security;',
    'alter table if exists provider_capabilities enable row level security;',
    'alter table if exists entity_prefix_registry enable row level security;',
    'alter table if exists id_registry enable row level security;',
    'alter table if exists foreign_key_registry enable row level security;',
  ].join('\n');
}

// P3: All policy names follow {table}_{role}_{operation} convention — NO collisions
// Each policy on each table has a UNIQUE name by including the operation (select/insert/update/delete)
function systemSqlPolicies() {
  return [
    '-- ============================================================',
    '-- 12. RLS POLICIES (P3 — Unique names per {table}_{role}_{operation})',
    '-- ============================================================',
    '',
    '-- schema_registry',
    'create policy schema_registry_admin_all on schema_registry for all to lexai_admin using (true) with check (true);',
    'create policy schema_registry_manager_select on schema_registry for select to lexai_manager using (true);',
    'create policy schema_registry_user_select on schema_registry for select to lexai_user using (true);',
    '',
    '-- entity_registry',
    'create policy entity_registry_admin_all on entity_registry for all to lexai_admin using (true) with check (true);',
    'create policy entity_registry_manager_select on entity_registry for select to lexai_manager using (true);',
    'create policy entity_registry_manager_insert on entity_registry for insert to lexai_manager with check (true);',
    'create policy entity_registry_manager_update on entity_registry for update to lexai_manager using (true);',
    'create policy entity_registry_user_select on entity_registry for select to lexai_user using (true);',
    '',
    '-- field_registry',
    'create policy field_registry_admin_all on field_registry for all to lexai_admin using (true) with check (true);',
    'create policy field_registry_manager_select on field_registry for select to lexai_manager using (true);',
    'create policy field_registry_manager_insert on field_registry for insert to lexai_manager with check (true);',
    'create policy field_registry_user_select on field_registry for select to lexai_user using (true);',
    '',
    '-- provider_registry',
    'create policy provider_registry_admin_all on provider_registry for all to lexai_admin using (true) with check (true);',
    'create policy provider_registry_manager_select on provider_registry for select to lexai_manager using (true);',
    '',
    '-- migration_registry',
    'create policy migration_registry_admin_all on migration_registry for all to lexai_admin using (true) with check (true);',
    'create policy migration_registry_manager_select on migration_registry for select to lexai_manager using (true);',
    '',
    '-- installer_state',
    'create policy installer_state_admin_all on installer_state for all to lexai_admin using (true) with check (true);',
    'create policy installer_state_manager_select on installer_state for select to lexai_manager using (true);',
    'create policy installer_state_user_select on installer_state for select to lexai_user using (true);',
    '',
    '-- provider_adapter_registry',
    'create policy provider_adapter_admin_all on provider_adapter_registry for all to lexai_admin using (true) with check (true);',
    'create policy provider_adapter_manager_select on provider_adapter_registry for select to lexai_manager using (true);',
    '',
    '-- schema_mapping',
    'create policy schema_mapping_admin_all on schema_mapping for all to lexai_admin using (true) with check (true);',
    'create policy schema_mapping_manager_select on schema_mapping for select to lexai_manager using (true);',
    'create policy schema_mapping_manager_insert on schema_mapping for insert to lexai_manager with check (true);',
    'create policy schema_mapping_manager_update on schema_mapping for update to lexai_manager using (true);',
    '',
    '-- mapping_history',
    'create policy mapping_history_admin_all on mapping_history for all to lexai_admin using (true) with check (true);',
    'create policy mapping_history_manager_select on mapping_history for select to lexai_manager using (true);',
    '',
    '-- mapping_versions',
    'create policy mapping_versions_admin_all on mapping_versions for all to lexai_admin using (true) with check (true);',
    'create policy mapping_versions_manager_select on mapping_versions for select to lexai_manager using (true);',
    '',
    '-- provider_capabilities',
    'create policy provider_capabilities_admin_all on provider_capabilities for all to lexai_admin using (true) with check (true);',
    'create policy provider_capabilities_manager_select on provider_capabilities for select to lexai_manager using (true);',
    'create policy provider_capabilities_user_select on provider_capabilities for select to lexai_user using (true);',
    '',
    '-- entity_prefix_registry',
    'create policy entity_prefix_admin_all on entity_prefix_registry for all to lexai_admin using (true) with check (true);',
    'create policy entity_prefix_manager_select on entity_prefix_registry for select to lexai_manager using (true);',
    'create policy entity_prefix_user_select on entity_prefix_registry for select to lexai_user using (true);',
    '',
    '-- id_registry',
    'create policy id_registry_admin_all on id_registry for all to lexai_admin using (true) with check (true);',
    'create policy id_registry_manager_select on id_registry for select to lexai_manager using (true);',
    '',
    '-- foreign_key_registry',
    'create policy foreign_key_registry_admin_all on foreign_key_registry for all to lexai_admin using (true) with check (true);',
    'create policy foreign_key_registry_manager_select on foreign_key_registry for select to lexai_manager using (true);',
  ].join('\n');
}

function systemSqlGrants() {
  return [
    '-- ============================================================',
    '-- 13. LEAST-PRIVILEGE GRANTS',
    '-- ============================================================',
    '',
    'grant usage on schema public to lexai_manager;',
    'grant select, insert, update, delete on all tables in schema public to lexai_manager;',
    'grant usage on all sequences in schema public to lexai_manager;',
    '',
    'grant usage on schema public to lexai_user;',
    'grant select on all tables in schema public to lexai_user;',
    '',
    'alter default privileges in schema public grant select, insert, update, delete on tables to lexai_manager;',
    'alter default privileges in schema public grant select on tables to lexai_user;',
    'alter default privileges in schema public grant usage on sequences to lexai_manager;',
  ].join('\n');
}

function systemSqlIndexes() {
  return [
    '-- ============================================================',
    '-- 14. INDEXES',
    '-- ============================================================',
    'create index if not exists idx_schema_registry_version on schema_registry (version);',
    'create index if not exists idx_field_registry_entity on field_registry (entity);',
    'create index if not exists idx_provider_registry_active on provider_registry (active);',
    'create index if not exists idx_provider_adapter_active on provider_adapter_registry (active);',
    'create index if not exists idx_schema_mapping_active on schema_mapping (active);',
    'create index if not exists idx_mapping_history_entity on mapping_history (entity_name);',
    'create index if not exists idx_provider_capabilities_provider on provider_capabilities (provider);',
    'create index if not exists idx_provider_capabilities_feature on provider_capabilities (feature);',
    'create index if not exists idx_entity_prefix_registry_prefix on entity_prefix_registry (prefix);',
    'create index if not exists idx_foreign_key_registry_from on foreign_key_registry (from_entity);',
    'create index if not exists idx_foreign_key_registry_to on foreign_key_registry (to_entity);',
  ].join('\n');
}

function systemSqlSchemaVersion() {
  const version = SCHEMA_VERSION;
  return [
    '-- ============================================================',
    '-- 15. SCHEMA VERSION STAMP',
    '-- ============================================================',
    `insert into schema_registry (id, version, description, applied_at)`,
    `values ('schema_version', ${version}, 'Schema v${version} — system infrastructure', now())`,
    "on conflict (id) do update set version = ${version}, description = excluded.description, applied_at = now();",
  ].join('\n');
}

function systemSqlSeedAdapters() {
  return [
    '-- ============================================================',
    '-- 16. SEED DEFAULT PROVIDER ADAPTERS',
    '-- ============================================================',
    "insert into provider_adapter_registry (id, provider, adapter_name, adapter_version, migration_engine, capabilities, active)",
    "values",
    "  ('ADP-supabase', 'supabase', 'SupabaseAdapter', '1.0.0', 'sql', '{\"exec_sql\":true,\"safe_ddl\":true,\"rls\":true,\"fk\":true,\"transactions\":true,\"json_support\":true}'::jsonb, true)",
    "on conflict (provider) do nothing;",
  ].join('\n');
}

const COMPILERS = { supabase: toSupabase, firebase: toFirebase, mongodb: toMongo, local: toLocal };

export const SchemaCompiler = {
  compile(provider, schemaOrName) {
    const schema = typeof schemaOrName === 'string' ? getSchema(schemaOrName) : schemaOrName;
    if (!schema) throw new Error(`Unknown schema: ${schemaOrName}`);
    const fn = COMPILERS[provider] || COMPILERS.local;
    return fn(schema);
  },

  compileAll(provider) {
    return listSchemas().map((s) => this.compile(provider, s));
  },

  installArtifact(provider) {
    const parts = this.compileAll(provider);
    if (provider === 'supabase') {
      const preDdl = this.systemSqlSections();
      const ddl = parts.map((p) => p.sql).join('\n\n');
      const postDdl = this.systemSqlPostDdl();
      return { kind: 'sql', schemaVersion: SCHEMA_VERSION, text: [preDdl, ddl, postDdl].join('\n\n') };
    }
    if (provider === 'firebase') {
      return {
        kind: 'firebase',
        schemaVersion: SCHEMA_VERSION,
        rules: `rules_version = '2';\nservice cloud.firestore {\n  match /databases/{database}/documents {\n${parts.map((p) => p.rules).join('\n')}\n  }\n}`,
        indexes: { indexes: parts.flatMap((p) => p.indexes) },
      };
    }
    if (provider === 'mongodb') {
      return {
        kind: 'mongodb',
        schemaVersion: SCHEMA_VERSION,
        mongoose: parts.map((p) => p.mongooseDefinition).join('\n\n'),
        validators: Object.fromEntries(parts.map((p) => [p.collection, p.jsonSchema])),
        indexes: Object.fromEntries(parts.map((p) => [p.collection, p.indexes])),
      };
    }
    return { kind: 'local', schemaVersion: SCHEMA_VERSION, collections: parts.map((p) => p.init) };
  },

  // P1: System SQL emitted in correct dependency order
  // P4: FK creation emitted AFTER all application DDL
  systemSqlSections() {
    const sections = [
      systemSqlRoles(),
      systemSqlMigrationRegistry(),
      systemSqlExecSql(),
      systemSqlSafeDdl(),
      systemSqlSafeCreateFk(),
      systemSqlRegistryTables(),
      systemSqlMappingTables(),
      systemSqlProviderTables(),
      systemSqlIdEngine(),
      systemSqlSupabaseAuth(),
    ];
    return sections.join('\n\n');
  },

  // P4: FK + RLS + Policies + Grants + Indexes (emitted after application DDL)
  systemSqlPostDdl() {
    return [
      systemSqlForeignKeys(),
      systemSqlRls(),
      systemSqlPolicies(),
      systemSqlGrants(),
      systemSqlIndexes(),
      systemSqlSchemaVersion(),
      systemSqlSeedAdapters(),
    ].join('\n\n');
  },
};

export default SchemaCompiler;
