import { listSchemas, getSchema, SCHEMA_VERSION } from './index.js';

const PG = { string: 'text', number: 'numeric', boolean: 'boolean', datetime: 'timestamptz', array: 'jsonb', object: 'jsonb', json: 'jsonb' };
const MONGOOSE = { string: 'String', number: 'Number', boolean: 'Boolean', datetime: 'Date', array: 'Array', object: 'Object', json: 'Object' };
const BSON = { string: 'string', number: 'number', boolean: 'bool', datetime: 'date', array: 'array', object: 'object', json: 'object' };
const FS = { string: 'string', number: 'number', boolean: 'bool', datetime: 'timestamp', array: 'list', object: 'map', json: 'map' };

const q = (id) => `"${id}"`;

function toSupabase(schema) {
  const cols = Object.entries(schema.fields).map(([name, type]) => {
    if (name === schema.primaryKey) return `  ${q(name)} text primary key`;
    return `  ${q(name)} ${PG[type] || 'text'}`;
  });
  const uniqueConstraints = (schema.uniqueConstraints || []).map(
    (uc) => `  constraint ${uc.name} unique (${q(uc.field)})`
  );
  const allCols = [...cols, ...uniqueConstraints];
  const createTable = `create table if not exists ${q(schema.collection)} (\n${allCols.join(',\n')}\n);`;
  const createIndexes = (schema.indexes || []).map(
    (f) => `create index if not exists ${`idx_${schema.collection}_${f}`} on ${q(schema.collection)} (${q(f)});`
  );
  const alterTable = (existingColumns = []) =>
    Object.entries(schema.fields)
      .filter(([name]) => !existingColumns.includes(name))
      .map(([name, type]) => `alter table ${q(schema.collection)} add column if not exists ${q(name)} ${name === schema.primaryKey ? 'text' : (PG[type] || 'text')};`);
  const alterLines = alterTable([]);
  return { provider: 'supabase', collection: schema.collection, createTable, createIndexes, alterTable, sql: [createTable, ...alterLines, ...createIndexes].join('\n') };
}

function toFirebase(schema) {
  const checks = Object.entries(schema.fields)
    .filter(([name]) => name !== schema.primaryKey)
    .map(([name, type]) => {
      const t = FS[type] || 'string';
      const present = `(!('${name}' in request.resource.data) || request.resource.data.${name} == null || request.resource.data.${name} is ${t})`;
      return `        ${present}`;
    });
  const required = (schema.required || []).map((f) => `        '${f}' in request.resource.data`);
  const rule = [
    `    match /${schema.collection}/{docId} {`,
    '      allow read: if true;',
    '      allow write: if',
    [...required, ...checks].join(' &&\n') || '        true',
    '      ;',
    '    }',
  ].join('\n');
  const indexes = (schema.indexes || []).map((f) => ({
    collectionGroup: schema.collection,
    queryScope: 'COLLECTION',
    fields: [{ fieldPath: f, order: 'ASCENDING' }],
  }));
  return {
    provider: 'firebase',
    collection: schema.collection,
    definition: { collection: schema.collection, fields: schema.fields, required: schema.required || [] },
    rules: rule,
    indexes,
  };
}

function toMongo(schema) {
  const defLines = Object.entries(schema.fields).map(([name, type]) => {
    const mt = MONGOOSE[type] || 'String';
    const idx = (schema.indexes || []).includes(name) ? ', index: true' : '';
    const uniq = name === schema.primaryKey ? ', unique: true' : '';
    return `  ${name}: { type: ${mt}${idx}${uniq} }`;
  });
  const mongooseDefinition =
    `// generated by SchemaCompiler — collection: ${schema.collection}\n` +
    `const ${schema.collection}Schema = new mongoose.Schema({\n${defLines.join(',\n')}\n}, { collection: '${schema.collection}', strict: false });`;

  const properties = {};
  Object.entries(schema.fields).forEach(([name, type]) => { properties[name] = { bsonType: BSON[type] || 'string' }; });
  const jsonSchema = {
    $jsonSchema: {
      bsonType: 'object',
      required: schema.required || [],
      properties,
    },
  };
  const indexes = [
    { key: { [schema.primaryKey]: 1 }, name: `${schema.primaryKey}_unique`, unique: true },
    ...(schema.indexes || []).map((f) => ({ key: { [f]: 1 }, name: `${f}_idx` })),
  ];
  return { provider: 'mongodb', collection: schema.collection, mongooseDefinition, jsonSchema, indexes };
}

function toLocal(schema) {
  return {
    provider: 'local',
    collection: schema.collection,
    init: { collection: schema.collection, fields: Object.keys(schema.fields), defaults: schema.defaults || {} },
  };
}

// P1/P5: Supabase compatibility — resolves auth.uid() to application role via users.role_code
function systemSqlSupabaseAuth() {
  return [
    '-- ============================================================',
    '-- 5a. SUPABASE AUTH COMPATIBILITY (P1/P5)',
    '-- ============================================================',
    '-- Maps auth.uid() → users.role_code for RLS policies without relying on',
    '-- browser users becoming PostgreSQL roles directly.',
    '--',
    '-- Usage in RLS policies:',
    '--   USING (current_user_role() = ANY(ARRAY[\'admin\', \'manager\']))',
    '--',
    '-- Falls back to \'anon\' when the calling user is not authenticated',
    '-- (auth.uid() IS NULL) or when the users table is not yet accessible.',
    '',
    'drop function if exists current_user_role() cascade;',
    'create or replace function current_user_role()',
    'returns text',
    'language plpgsql',
    'security definer',
    'stable',
    "set search_path = 'public'",
    'as $$',
    'declare',
    '  v_role text;',
    'begin',
    '  -- Try Supabase auth.uid()',
    '  begin',
    '    if auth.uid() is null then',
    '      -- Not authenticated via Supabase — check pg role',
    '      if current_user = \'anon\' then return \'anon\'; end if;',
    '      if current_user = \'service_role\' then return \'admin\'; end if;',
    '      return \'anon\';',
    '    end if;',
    '    -- Prefer lightweight user_role_registry (avoids full users table scan + RLS recursion)',
    '    if exists (select 1 from pg_class where relname = \'user_role_registry\') then',
    "      select role_code into v_role from user_role_registry where user_id = auth.uid()::text;",
    '      if found then return v_role; end if;',
    '    end if;',
    '    -- Fallback to users table',
    "    select role_code into strict v_role from users where id = auth.uid()::text;",
    '    return v_role;',
    '  exception',
    '    when others then',
    '      -- If neither table is accessible, fall back to role name',
    '      if current_user = \'authenticated\' then return \'user\'; end if;',
    '      return \'anon\';',
    '  end;',
    'end;',
    '$$;',
  ].join('\n');
}

// P5: verify_installation — comprehensive schema health check
function systemSqlVerifyInstallation() {
  return [
    '-- ============================================================',
    '-- 5b. INSTALLATION VERIFICATION (P5)',
    '-- ============================================================',
    '-- Returns JSONB with per-component health status.',
    '',
    'drop function if exists verify_installation() cascade;',
    'create or replace function verify_installation()',
    'returns jsonb',
    'language plpgsql',
    'security definer',
    'as $$',
    'declare',
    '  v_result jsonb;',
    '  v_schema boolean;',
    '  v_mappings boolean;',
    '  v_providers boolean;',
    '  v_functions boolean;',
    '  v_fks boolean;',
    '  v_security boolean;',
    '  v_ready boolean;',
    'begin',
    '  -- Schema/registry tables',
    '  select count(*) = 13 into v_schema from pg_class where relname in (',
    '    \'migration_registry\', \'schema_registry\', \'entity_registry\', \'field_registry\',',
    "    'provider_registry', 'provider_adapter_registry', 'installer_state',",
    "    'entity_prefix_registry', 'id_registry', 'foreign_key_registry', 'schema_mapping', 'mapping_versions', 'user_role_registry'",
    '  ) and relkind = \'r\';',
    '',
    '  -- Mapping tables',
    '  select count(*) = 3 into v_mappings from pg_class where relname in (',
    "    'schema_mapping', 'mapping_history', 'mapping_versions'",
    '  ) and relkind = \'r\';',
    '',
    '  -- Provider tables',
    '  select count(*) = 2 into v_providers from pg_class where relname in (',
    "    'provider_registry', 'provider_capabilities'",
    '  ) and relkind = \'r\';',
    '',
    '  -- Required functions',
    '  select count(*) = 7 into v_functions from pg_proc where proname in (',
    "    'exec_sql', 'safe_ddl', 'safe_create_fk', 'next_lx_id', 'current_user_role',",
    "    'resolve_entity_table', 'sync_user_role_registry'",
    '  );',
    '',
    '  -- Foreign keys — compare foreign_key_registry entries against actual constraints',
    '  select',
    '    case',
    '      when not exists (select 1 from pg_class where relname = \'foreign_key_registry\') then false',
    '      else (',
    '        select count(*) >= 1 and count(*) = (',
    '          select count(*) from foreign_key_registry where enabled = true',
    '        )',
    '        from pg_constraint c',
    '        join pg_class t on t.oid = c.conrelid',
    "        where c.contype = 'f'",
    '      )',
    '    end',
    '  into v_fks;',
    '',
    '  -- Security: RLS enabled, policies exist, functions granted',
    '  select',
    '    count(*) >= 13 and',
    "    exists (select 1 from pg_policy) and",
    "    exists (select 1 from pg_proc where proname = 'current_user_role')",
    '  into v_security',
    '  from pg_class where relrowsecurity = true;',
    '',
    '  v_ready := v_schema and v_mappings and v_functions and v_security;',
    '',
    '  v_result := jsonb_build_object(',
    "    'schema', v_schema,",
    "    'mappings', v_mappings,",
    "    'providers', v_providers,",
    "    'functions', v_functions,",
    "    'foreignKeys', v_fks,",
    "    'security', v_security,",
    "    'ready', v_ready",
    '  );',
    '  return v_result;',
    'end;',
    '$$;',
    '',
    "do $$ begin if exists (select 1 from pg_roles where rolname = 'authenticated') then grant execute on function verify_installation() to authenticated; end if; end $$;",
    "do $$ begin if exists (select 1 from pg_roles where rolname = 'anon') then grant execute on function verify_installation() to anon; end if; end $$;",
  ].join('\n');
}

// ---- System infrastructure SQL sections (emitted in dependency order) -----
// P1: migration_registry created FIRST so exec_sql/safe_ddl can audit into it
// P4: FK creation extracted to separate method, called AFTER all tables exist

function systemSqlMigrationRegistry() {
  return [
    '-- ============================================================',
    '-- 2. migration_registry — audit log of all schema migrations',
    '-- Created FIRST so exec_sql/safe_ddl can write audit entries.',
    '-- ============================================================',
    'create table if not exists migration_registry (',
    '  id text primary key default gen_random_uuid()::text,',
    '  version integer not null,',
    '  description text,',
    '  sql_hash text,',
    '  applied_at timestamptz default now(),',
    '  duration_ms integer default 0,',
    '  success boolean default true,',
    '  error text,',
    "  action text default 'migrate'",
    ');',
    '',
    "create index if not exists idx_migration_registry_version on migration_registry (version);",
    "create index if not exists idx_migration_registry_applied_at on migration_registry (applied_at);",
  ].join('\n');
}

function systemSqlExecSql() {
  return [
    '-- ============================================================',
    '-- 3. exec_sql — DDL/query execution (security definer — caller assumes owner role)',
    '-- ============================================================',
    '-- Returns setof jsonb so callers can read query results (VerificationEngine, DDL service).',
    '-- For SELECT queries, returns the result rows as JSONB objects.',
    '-- For DDL, returns a single {"ok": true} row.',
    '-- NOTE: Granted to anon + authenticated for Copy-Paste wizard verification.',
    '-- Revoke from anon after initial setup if desired.',
    '',
    'create or replace function exec_sql(sql text)',
    'returns setof jsonb',
    'language plpgsql',
    'security definer',
    'as $$',
    'begin',
    '  if exists (select 1 from pg_tables where tablename = \'migration_registry\') then',
    "    insert into migration_registry (id, version, description, sql_hash, applied_at, duration_ms, success)",
    "    values (gen_random_uuid()::text, 0, 'exec_sql', md5(sql), now(), 0, true);",
    '  end if;',
    '  return query execute sql;',
    'exception',
    '  when others then',
    '    execute sql;',
    "    return query select '{\"ok\":true}'::jsonb;",
    'end;',
    '$$;',
  ].join('\n');
}

// P2: All regex patterns use correct \\s for whitespace in PostgreSQL regex
function systemSqlSafeDdl() {
  return [
    '-- ============================================================',
    '-- 4. safe_ddl — allowlisted DDL execution for admin/manager via current_user_role()',
    '-- ============================================================',
    '-- Blocklist: DROP, TRUNCATE, ALTER TABLE DROP, GRANT/REVOKE, DML,',
    '--            CREATE DATABASE/SCHEMA/ROLE/USER/EXTENSION,',
    '--            ALTER DATABASE/SCHEMA/ROLE/USER, REINDEX, CLUSTER, VACUUM, ANALYZE',
    '-- Allowlist: CREATE TABLE IF NOT EXISTS, CREATE INDEX IF NOT EXISTS,',
    '--            ALTER TABLE ADD COLUMN IF NOT EXISTS, ALTER TABLE ADD CONSTRAINT,',
    '--            CREATE OR REPLACE FUNCTION, ALTER TABLE IF EXISTS,',
    '--            ALTER TABLE ... ENABLE/DISABLE ROW LEVEL SECURITY,',
    '--            CREATE/ALTER/DROP POLICY, COMMENT ON, DO $$ blocks',
    '-- P2: All \\s patterns correctly escaped for PostgreSQL POSIX regex.',
    '-- Uses IF EXISTS guard on migration_registry INSERT.',
    '',
    'create or replace function safe_ddl(sql text)',
    'returns void',
    'language plpgsql',
    'security definer',
    'as $$',
    'declare',
    '  v_upper text;',
    'begin',
    '  v_upper := upper(sql);',
    '',
    '  -- Blocklist (checked before allowlist)',
    "  if v_upper ~ '^\\s*DROP\\s+(DATABASE|SCHEMA|TABLE|VIEW|FUNCTION|INDEX|ROLE|POLICY|TRIGGER|EXTENSION|PUBLICATION|SUBSCRIPTION)' then",
    "    raise exception 'safe_ddl: DROP is not permitted';",
    '  end if;',
    "  if v_upper ~ '^\\s*TRUNCATE' then",
    "    raise exception 'safe_ddl: TRUNCATE is not permitted';",
    '  end if;',
    "  if v_upper ~ 'ALTER\\s+TABLE.*DROP\\s+(COLUMN|CONSTRAINT)' then",
    "    raise exception 'safe_ddl: ALTER TABLE DROP is not permitted';",
    '  end if;',
    "  if v_upper ~ '^\\s*(GRANT|REVOKE)' then",
    "    raise exception 'safe_ddl: GRANT/REVOKE is not permitted';",
    '  end if;',
    "  if v_upper ~ '^\\s*(DELETE|UPDATE|INSERT|TRUNCATE)\\s' then",
    "    raise exception 'safe_ddl: DML statements are not permitted; use CRUD APIs';",
    '  end if;',
    "  if v_upper ~ '^\\s*CREATE\\s+(DATABASE|SCHEMA|ROLE|USER|EXTENSION)\\s' then",
    "    raise exception 'safe_ddl: CREATE DATABASE/SCHEMA/ROLE/USER/EXTENSION is not permitted';",
    '  end if;',
    "  if v_upper ~ '^\\s*ALTER\\s+(DATABASE|SCHEMA|ROLE|USER)\\s' then",
    "    raise exception 'safe_ddl: ALTER DATABASE/SCHEMA/ROLE/USER is not permitted';",
    '  end if;',
    '',
    '  -- Allowlist',
    '  if not (',
    "    v_upper ~ '^\\s*CREATE\\s+TABLE\\s+IF\\s+NOT\\s+EXISTS\\s' or",
    "    v_upper ~ '^\\s*CREATE\\s+INDEX\\s+IF\\s+NOT\\s+EXISTS\\s' or",
    "    v_upper ~ 'ALTER\\s+TABLE.*ADD\\s+COLUMN\\s+IF\\s+NOT\\s+EXISTS' or",
    "    v_upper ~ 'ALTER\\s+TABLE.*ADD\\s+CONSTRAINT' or",
    "    v_upper ~ '^\\s*CREATE\\s+OR\\s+REPLACE\\s+FUNCTION\\s' or",
    "    v_upper ~ '^\\s*ALTER\\s+TABLE\\s+IF\\s+EXISTS\\s' or",
    "    v_upper ~ 'ALTER\\s+TABLE.*ENABLE\\s+ROW\\s+LEVEL\\s+SECURITY' or",
    "    v_upper ~ 'ALTER\\s+TABLE.*DISABLE\\s+ROW\\s+LEVEL\\s+SECURITY' or",
    "    v_upper ~ '^\\s*CREATE\\s+POLICY\\s' or",
    "    v_upper ~ '^\\s*ALTER\\s+POLICY\\s' or",
    "    v_upper ~ '^\\s*DROP\\s+POLICY\\s+IF\\s+EXISTS\\s' or",
    "    v_upper ~ '^\\s*COMMENT\\s+ON\\s' or",
    "    v_upper ~ '^\\s*DO\\s+\\$\\$' or",
    "    v_upper ~ '^\\s*--'",
    '  ) then',
    "    raise exception 'safe_ddl: Statement does not match any allowed pattern: %', substr(sql, 1, 80);",
    '  end if;',
    '',
    '  -- Audit (with IF EXISTS guard so migration_registry need not exist yet)',
    '  if exists (select 1 from pg_tables where tablename = \'migration_registry\') then',
    "    insert into migration_registry (id, version, description, sql_hash, applied_at, duration_ms, success)",
    "    values (gen_random_uuid()::text, 0, 'safe_ddl', md5(sql), now(), 0, true);",
    '  end if;',
    '  execute sql;',
    'end;',
    '$$;',
    '',
    "do $$ begin if exists (select 1 from pg_roles where rolname = 'authenticated') then grant execute on function exec_sql(text) to authenticated; end if; end $$;",
    "do $$ begin if exists (select 1 from pg_roles where rolname = 'anon') then grant execute on function exec_sql(text) to anon; end if; end $$;",
    "do $$ begin if exists (select 1 from pg_roles where rolname = 'authenticated') then grant execute on function safe_ddl(text) to authenticated; end if; end $$;",
    "do $$ begin if exists (select 1 from pg_roles where rolname = 'anon') then grant execute on function safe_ddl(text) to anon; end if; end $$;",
  ].join('\n');
}

function systemSqlSafeCreateFk() {
  return [
    '-- ============================================================',
    '-- 5. SAFE FOREIGN KEY HELPER (P4 — hardened ON DELETE validation)',
    '-- ============================================================',
    '-- safe_create_fk — creates a foreign key only if the referenced table,',
    '-- referenced column, and source column all exist and the FK does not',
    '-- already exist. Never fails on missing references.',
    '--',
    '-- P4: p_on_delete is validated against the allowlist before format().',
    '--      Rejects anything outside: CASCADE, SET NULL, RESTRICT, NO ACTION, SET DEFAULT.',
    '--      Prevents SQL injection through the ON DELETE parameter.',
    '',
    'create or replace function safe_create_fk(',
    '  p_source_table text,',
    '  p_source_column text,',
    '  p_target_table text,',
    '  p_target_column text,',
    '  p_constraint_name text,',
    "  p_on_delete text default 'CASCADE'",
    ') returns void',
    'language plpgsql',
    'as $safe_fk$',
    'declare',
    '  v_exists boolean;',
    '  v_upper_on_delete text;',
    'begin',
    '  -- P4: validate ON DELETE action before any processing',
    '  v_upper_on_delete := upper(p_on_delete);',
    '  if v_upper_on_delete not in (\'CASCADE\', \'SET NULL\', \'RESTRICT\', \'NO ACTION\', \'SET DEFAULT\') then',
    "    raise exception 'safe_create_fk: invalid ON DELETE action: % (must be CASCADE, SET NULL, RESTRICT, NO ACTION, or SET DEFAULT)', p_on_delete;",
    '  end if;',
    '  -- Resolve entity names → provider table names via schema_mapping',
    '  if exists (select 1 from pg_proc where proname = \'resolve_entity_table\') then',
    '    p_source_table := resolve_entity_table(p_source_table);',
    '    p_target_table := resolve_entity_table(p_target_table);',
    '  end if;',
    '  select exists (',
    '    select 1 from pg_constraint c',
    '    join pg_class t on t.oid = c.conrelid',
    '    where t.relname = p_source_table',
    '    and c.conname = p_constraint_name',
    '  ) into v_exists;',
    '  if v_exists then return; end if;',
    '  if not exists (select 1 from pg_class where relname = p_source_table) then return; end if;',
    '  if not exists (select 1 from pg_class where relname = p_target_table) then return; end if;',
    '  if not exists (',
    '    select 1 from pg_attribute a',
    '    join pg_class t on t.oid = a.attrelid',
    '    where t.relname = p_source_table',
    '    and a.attname = p_source_column',
    '    and a.attnum > 0',
    '  ) then return; end if;',
    '  if not exists (',
    '    select 1 from pg_attribute a',
    '    join pg_class t on t.oid = a.attrelid',
    '    where t.relname = p_target_table',
    '    and a.attname = p_target_column',
    '    and a.attnum > 0',
    '  ) then return; end if;',
    '  execute format($fmt$',
    '    alter table %I add constraint %I',
    '    foreign key (%I) references %I (%I) on delete %s',
    '  $fmt$, p_source_table, p_constraint_name, p_source_column, p_target_table, p_target_column, v_upper_on_delete);',
    '  insert into foreign_key_registry (id, from_entity, from_field, to_entity, to_field, cascade_delete, enabled)',
    "  values (p_constraint_name, p_source_table, p_source_column, p_target_table, p_target_column, p_on_delete = 'CASCADE', true)",
    '  on conflict (id) do nothing;',
    'end;',
    '$safe_fk$;',
  ].join('\n');
}

// resolve_entity_table — looks up schema_mapping to resolve LexAI entity name → provider table name
// Falls back to the entity name itself when no mapping exists or table is not yet created.
// Used by safe_create_fk so FK definitions can use entity names instead of hardcoded table names.
function systemSqlResolveEntity() {
  return [
    '-- ============================================================',
    '-- 5a. ENTITY RESOLUTION (entity_registry + schema_mapping lookup)',
    '-- ============================================================',
    'create or replace function resolve_entity_table(p_entity text)',
    'returns text',
    'language plpgsql',
    'stable',
    'as $$',
    'declare',
    '  v_table text;',
    'begin',
    "  if exists (select 1 from pg_class where relname = 'schema_mapping') then",
    "    select provider_table into v_table from schema_mapping",
    "    where entity_name = p_entity and active = true",
    '    limit 1;',
    '    if found then return v_table; end if;',
    '  end if;',
    '  return p_entity;',
    'end;',
    '$$;',
    '',
    "do $$ begin if exists (select 1 from pg_roles where rolname = 'authenticated') then grant execute on function resolve_entity_table(text) to authenticated; end if; end $$;",
  ].join('\n');
}

// user_role_registry — lightweight role lookup table to avoid querying full users table
// Kept in sync via trigger (created post-DDL). current_user_role() queries this first.
function systemSqlUserRoleRegistry() {
  return [
    '-- ============================================================',
    '-- 5b. USER ROLE REGISTRY (lightweight role lookup, avoids RLS recursion on users)',
    '-- ============================================================',
    'create table if not exists user_role_registry (',
    '  user_id text primary key,',
    '  role_code text not null,',
    '  updated_at timestamptz default now()',
    ');',
    'alter table user_role_registry enable row level security;',
    '',
    '-- Admin-only policy on user_role_registry (lookup is via security-definer function)',
    "create policy user_role_registry_admin_all on user_role_registry for all to authenticated using (current_user_role() = 'admin') with check (current_user_role() = 'admin');",
  ].join('\n');
}

// user_role_registry sync trigger — created post-DDL after users table exists
function systemSqlUserRoleTrigger() {
  return [
    '-- ============================================================',
    '-- 5b-sync. USER ROLE REGISTRY SYNC TRIGGER (post-DDL, depends on users table)',
    '-- ============================================================',
    'drop function if exists sync_user_role_registry() cascade;',
    "create or replace function sync_user_role_registry()",
    'returns trigger',
    'language plpgsql',
    'security definer',
    'as $$',
    'begin',
    "  if exists (select 1 from pg_class where relname = 'user_role_registry') then",
    '    if tg_op = \'DELETE\' then',
    '      delete from user_role_registry where user_id = old.id;',
    '      return old;',
    '    end if;',
    "    insert into user_role_registry (user_id, role_code, updated_at)",
    "    values (new.id, new.role_code, now())",
    "    on conflict (user_id) do update set role_code = excluded.role_code, updated_at = now();",
    '  end if;',
    '  return new;',
    'end;',
    '$$;',
    '',
    'do $$ begin',
    "  if exists (select 1 from pg_class where relname = 'users' and relkind = 'r') then",
    '    drop trigger if exists trg_user_role_registry_sync on users;',
    '  end if;',
    'end;',
    '$$;',
    '',
    'create trigger trg_user_role_registry_sync',
    'after insert or update or delete on users',
    'for each row execute function sync_user_role_registry();',
    '',
    '-- Seed existing roles into user_role_registry',
    "insert into user_role_registry (user_id, role_code, updated_at)",
    "select id, role_code, now() from users",
    "on conflict (user_id) do nothing;",
  ].join('\n');
}

// P4: FK creation calls extracted — emitted AFTER all application tables exist
function systemSqlForeignKeys({ onlyCollections } = {}) {
  const ALL_FKS = [
    { from: 'reminders', to: 'cases', fk: 'fk_reminders_case_id' },
    { from: 'notes', to: 'cases', fk: 'fk_notes_case_id' },
    { from: 'hearings', to: 'cases', fk: 'fk_hearings_case_id' },
    { from: 'drafts', to: 'cases', fk: 'fk_drafts_case_id' },
    { from: 'documents', to: 'cases', fk: 'fk_documents_case_id' },
    { from: 'case_history', to: 'cases', fk: 'fk_case_history_case_id' },
    { from: 'case_folders', to: 'cases', fk: 'fk_case_folders_case_id' },
    { from: 'case_activity', to: 'cases', fk: 'fk_case_activity_case_id' },
    { from: 'audit_logs', to: 'users', fk: 'fk_audit_logs_user_id' },
    { from: 'users', to: 'roles', fk: 'fk_users_role_code' },
    { from: 'case_folders', to: 'case_folders', fk: 'fk_case_folders_parent_id' },
  ];
  const fkLines = ALL_FKS.map(({ from, to, fk }) => {
    const cascade = fk === 'fk_audit_logs_user_id' ? ', \'SET NULL\'' : ', \'CASCADE\'';
    if (fk === 'fk_users_role_code') {
      return "select safe_create_fk('users', 'role_code', 'roles', 'code', 'fk_users_role_code', 'RESTRICT');";
    }
    const sourceCol = fk === 'fk_case_folders_parent_id' ? 'parent_id' : 'case_id';
    return `select safe_create_fk('${from}', '${sourceCol}', '${to}', 'id', '${fk}'${cascade});`;
  });
  const filtered = onlyCollections ? ALL_FKS.filter(({ from, to }) => onlyCollections.includes(from) || onlyCollections.includes(to)) : ALL_FKS;
  const lines = filtered.map(({ from, to, fk }) => {
    if (fk === 'fk_users_role_code') {
      return "select safe_create_fk('users', 'role_code', 'roles', 'code', 'fk_users_role_code', 'RESTRICT');";
    }
    const cascade = fk === 'fk_audit_logs_user_id' ? ', \'SET NULL\'' : ', \'CASCADE\'';
    const sourceCol = fk === 'fk_case_folders_parent_id' ? 'parent_id' : 'case_id';
    return `select safe_create_fk('${from}', '${sourceCol}', '${to}', 'id', '${fk}'${cascade});`;
  });
  return [
    '-- ============================================================',
    '-- 6. FOREIGN KEY INSTALLATION (P4 — after all tables exist)',
    '-- ============================================================',
    '-- All safe_create_fk calls run after registry tables AND application',
    '-- tables are created, so referenced tables/columns are guaranteed to exist.',
    '-- uq_roles_code unique constraint is defined inline in the CREATE TABLE for roles (see roles.schema.js).',
    ...lines,
  ].join('\n');
}

function systemSqlRegistryTables() {
  return [
    '-- ============================================================',
    '-- 7. REGISTRY TABLES',
    '-- ============================================================',
    '',
    '-- schema_registry — tracks schema versions & migrations applied',
    'create table if not exists schema_registry (',
    '  id text primary key default gen_random_uuid()::text,',
    '  version integer not null default 0,',
    '  description text,',
    '  checksum text,',
    "  applied_at timestamptz default now(),",
    "  applied_by text default current_user",
    ');',
    '',
    '-- entity_registry — registered entity definitions',
    'create table if not exists entity_registry (',
    '  id text primary key default gen_random_uuid()::text,',
    '  name text not null unique,',
    '  label text,',
    '  table_name text not null,',
    "  primary_key text default 'id',",
    '  core boolean default false,',
    "  fields jsonb default '{}'::jsonb,",
    "  indexes jsonb default '{}'::jsonb,",
    "  created_at timestamptz default now(),",
    "  updated_at timestamptz default now()",
    ');',
    '',
    '-- field_registry — field-level metadata per entity',
    'create table if not exists field_registry (',
    '  id text primary key default gen_random_uuid()::text,',
    '  entity text not null,',
    '  field_name text not null,',
    '  field_type text not null,',
    '  required boolean default false,',
    '  unique_field boolean default false,',
    '  default_value text,',
    "  created_at timestamptz default now()",
    ');',
    '',
    '-- provider_registry — database provider configuration',
    'create table if not exists provider_registry (',
    '  id text primary key default gen_random_uuid()::text,',
    '  provider_type text not null,',
    '  label text,',
    "  config jsonb default '{}'::jsonb,",
    '  active boolean default true,',
    '  connected_at timestamptz,',
    "  created_at timestamptz default now(),",
    "  updated_at timestamptz default now()",
    ');',
    '',
    '-- installer_state — instantaneous installation tracking',
    'create table if not exists installer_state (',
    "  id text primary key default 'default',",
    "  install_status text not null default 'none' check (install_status in ('none', 'in_progress', 'completed', 'failed')),",
    '  schema_version integer not null default 0,',
    '  installer_version integer not null default 1,',
    '  provider text,',
    '  database_type text,',
    '  verified_at timestamptz,',
    '  installed_at timestamptz,',
    "  updated_at timestamptz default now()",
    ');',
  ].join('\n');
}

function systemSqlMappingTables() {
  return [
    '-- ============================================================',
    '-- 8. SCHEMA MAPPING TABLES',
    '-- ============================================================',
    '',
    '-- schema_mapping — LexAI entity name ↔ provider table name',
    'create table if not exists schema_mapping (',
    '  id text primary key default gen_random_uuid()::text,',
    '  entity_name text not null unique,',
    '  provider_table text not null,',
    '  description text,',
    '  active boolean default true,',
    '  version integer not null default 1,',
    "  created_at timestamptz default now(),",
    "  updated_at timestamptz default now()",
    ');',
    '',
    '-- mapping_history — audit log of mapping changes',
    'create table if not exists mapping_history (',
    '  id text primary key default gen_random_uuid()::text,',
    '  entity_name text not null,',
    '  old_table text,',
    '  new_table text not null,',
    '  changed_by text,',
    '  change_reason text,',
    "  created_at timestamptz default now()",
    ');',
    '',
    '-- mapping_versions — versioned snapshots of the entire mapping set',
    'create table if not exists mapping_versions (',
    '  id text primary key default gen_random_uuid()::text,',
    '  version integer not null,',
    '  snapshot jsonb not null,',
    '  description text,',
    "  created_at timestamptz default now()",
    ');',
    '',
    '-- provider_capabilities — feature detection per provider',
    'create table if not exists provider_capabilities (',
    '  id text primary key default gen_random_uuid()::text,',
    '  provider text not null,',
    '  feature text not null,',
    '  supported boolean not null default false,',
    "  metadata jsonb default '{}'::jsonb,",
    "  detected_at timestamptz default now()",
    ');',
  ].join('\n');
}

function systemSqlProviderTables() {
  return [
    '-- ============================================================',
    '-- 9. PROVIDER ADAPTER + ENTITY PREFIX TABLES',
    '-- ============================================================',
    '',
    '-- provider_adapter_registry — dynamic adapter loading',
    'create table if not exists provider_adapter_registry (',
    '  id text primary key default gen_random_uuid()::text,',
    '  provider text not null unique,',
    '  adapter_name text not null,',
    "  adapter_version text not null default '1.0.0',",
    "  migration_engine text default 'sql',",
    "  capabilities jsonb default '{}'::jsonb,",
    '  active boolean default true,',
    "  config jsonb default '{}'::jsonb,",
    "  created_at timestamptz default now(),",
    "  updated_at timestamptz default now()",
    ');',
    '',
    '-- entity_prefix_registry — LX-ID prefix management',
    'create table if not exists entity_prefix_registry (',
    '  entity text primary key,',
    '  prefix text not null,',
    '  label text,',
    '  padding integer not null default 5,',
    '  current_sequence integer not null default 0,',
    "  created_at timestamptz default now(),",
    "  updated_at timestamptz default now()",
    ');',
    '',
    '-- id_registry — backward-compatible ID tracking',
    'create table if not exists id_registry (',
    '  entity text primary key,',
    '  prefix text not null,',
    '  sequence integer not null default 0,',
    "  created_at timestamptz default now(),",
    "  updated_at timestamptz default now()",
    ');',
    '',
    '-- foreign_key_registry — tracks FK relationships across entities',
    'create table if not exists foreign_key_registry (',
    '  id text primary key default gen_random_uuid()::text,',
    '  from_entity text not null,',
    '  from_field text not null,',
    '  to_entity text not null,',
    "  to_field text not null default 'id',",
    '  cascade_delete boolean default false,',
    '  enabled boolean default true,',
    "  created_at timestamptz default now()",
    ');',
  ].join('\n');
}

function systemSqlIdEngine() {
  return [
    '-- ============================================================',
    '-- 10. LX-ID SEQUENCE MANAGER',
    '-- ============================================================',
    '-- Generates LX-{PREFIX}-{SEQUENCE} using the entity_prefix_registry',
    '',
    'create or replace function next_lx_id(p_entity text)',
    'returns text',
    'language plpgsql',
    'as $$',
    'declare',
    '  v_prefix text;',
    '  v_pad int;',
    '  v_seq int;',
    '  v_id text;',
    'begin',
    "  insert into entity_prefix_registry (entity, prefix, label, padding, current_sequence)",
    "  values (p_entity, upper(substr(p_entity, 1, 5)), p_entity, 5, 0)",
    '  on conflict (entity) do nothing;',
    '  select prefix, padding into strict v_prefix, v_pad from entity_prefix_registry where entity = p_entity;',
    '  update entity_prefix_registry',
    '  set current_sequence = current_sequence + 1,',
    '      updated_at = now()',
    '  where entity = p_entity',
    '  returning current_sequence into v_seq;',
    "  v_id := 'LX-' || v_prefix || '-' || lpad(v_seq::text, v_pad, '0');",
    '  return v_id;',
    'end;',
    '$$;',
  ].join('\n');
}

const APP_TABLES = [
  'users', 'roles', 'permissions', 'cases', 'courts', 'case_types', 'case_stages',
  'reminders', 'notes', 'hearings', 'drafts', 'documents', 'case_history', 'case_folders',
  'case_activity', 'audit_logs', 'config_history', 'settings', 'env_vars', 'schema_meta',
  'judgments', 'cause_list_templates', 'bench_types', 'jurisdictions',
  'clients', 'contacts', 'acts', 'prompts', 'templates', 'legal_notices', 'precedents', 'reports',
  'party_types', 'case_statuses', 'priorities', 'hearing_statuses', 'contact_types',
  'judges', 'reminder_types', 'folder_templates', 'draft_types', 'area_of_law',
  'type_of_proceeding', 'nature_of_dispute', 'provisions',
];

function systemSqlRls({ onlyCollections } = {}) {
  const SYSTEM_TABLES = [
    'schema_registry', 'entity_registry', 'field_registry', 'provider_registry',
    'migration_registry', 'installer_state', 'provider_adapter_registry',
    'schema_mapping', 'mapping_history', 'mapping_versions', 'provider_capabilities',
    'entity_prefix_registry', 'id_registry', 'foreign_key_registry', 'user_role_registry',
  ];
  const appTables = onlyCollections
    ? APP_TABLES.filter((t) => onlyCollections.includes(t))
    : APP_TABLES;
  const allTables = [...SYSTEM_TABLES, ...appTables];
  return [
    '-- ============================================================',
    '-- 11. ROW LEVEL SECURITY',
    '-- ============================================================',
    '-- Enable RLS on tables (registry + application)',
    ...allTables.map((t) => `alter table if exists ${t} enable row level security;`),
  ].join('\n');
}

// P2: Policies target TO authenticated (Supabase-compatible) and use current_user_role()
// P3: All policy names follow {table}_{role}_{operation} convention — NO collisions
// Each policy on each table has a UNIQUE name by including the operation (select/insert/update/delete)
const SYSTEM_POLICY_TABLES = [
  'schema_registry', 'entity_registry', 'field_registry', 'provider_registry',
  'migration_registry', 'installer_state', 'provider_adapter_registry',
  'schema_mapping', 'mapping_history', 'mapping_versions', 'provider_capabilities',
  'entity_prefix_registry', 'id_registry', 'foreign_key_registry', 'user_role_registry',
];

const APP_POLICY_TABLES = [
  'users', 'roles', 'permissions', 'cases', 'documents', 'hearings', 'notes',
  'reminders', 'drafts', 'case_history', 'case_activity', 'case_folders',
  'settings', 'env_vars', 'audit_logs', 'config_history', 'schema_meta',
  'courts', 'case_types', 'case_stages', 'judgments', 'cause_list_templates',
  'bench_types', 'jurisdictions',
  'clients', 'contacts', 'acts', 'prompts', 'templates', 'legal_notices', 'precedents', 'reports',
  'party_types', 'case_statuses', 'priorities', 'hearing_statuses', 'contact_types',
  'judges', 'reminder_types', 'folder_templates', 'draft_types', 'area_of_law',
  'type_of_proceeding', 'nature_of_dispute', 'provisions',
];

function systemSqlPolicies({ onlyCollections } = {}) {
  const keepTable = (table) => {
    if (SYSTEM_POLICY_TABLES.includes(table)) return true;
    if (onlyCollections) return onlyCollections.includes(table);
    return APP_POLICY_TABLES.includes(table);
  };

  const adminAll = (t) => `create policy ${t}_admin_all on ${t} for all to authenticated using (current_user_role() = 'admin') with check (current_user_role() = 'admin');`;
  const adminSelect = (t) => `create policy ${t}_admin_select on ${t} for select to authenticated using (current_user_role() = 'admin');`;
  const managerAll = (t) => `create policy ${t}_manager_all on ${t} for all to authenticated using (current_user_role() = ANY(ARRAY['admin','manager'])) with check (current_user_role() = ANY(ARRAY['admin','manager']));`;
  const managerSelect = (t) => `create policy ${t}_manager_select on ${t} for select to authenticated using (current_user_role() = ANY(ARRAY['admin','manager']));`;
  const userSelect = (t) => `create policy ${t}_user_select on ${t} for select to authenticated using (current_user_role() = ANY(ARRAY['admin','manager','user']));`;
  const anonSelect = (t) => `do $$ begin if exists (select 1 from pg_roles where rolname = 'anon') then execute 'drop policy if exists ${t}_anon_select on ${t}'; execute 'create policy ${t}_anon_select on ${t} for select to anon using (true)'; end if; end $$;`;

  const allTables = [
    ...SYSTEM_POLICY_TABLES.map(t => ({ table: t, kind: 'system' })),
    ...APP_POLICY_TABLES.map(t => ({ table: t, kind: 'app' })),
  ];

  const lines = [];
  for (const { table, kind } of allTables) {
    if (!keepTable(table)) continue;

    const drop = `drop policy if exists`;
    const policy = (name) => `${drop} ${name} on ${table};`;

    if (table === 'users') {
      lines.push(`-- ${table} (sensitive — admin/manager full, user read own, anon registration)`);
      lines.push(policy(`${table}_admin_all`) + '\n' + adminAll(table));
      lines.push(policy(`${table}_manager_all`) + '\n' + managerAll(table));
      lines.push(policy(`${table}_user_select`) + '\n' + userSelect(table));
      lines.push(anonSelect(table));
      lines.push(`do $$ begin if exists (select 1 from pg_roles where rolname = 'anon') then execute $p$drop policy if exists ${table}_anon_insert on ${table}$p$; execute $p$create policy ${table}_anon_insert on ${table} for insert to anon with check (not exists (select 1 from ${table}))$p$; end if; end $$;`);
      lines.push(`grant insert on table ${table} to anon;`);
      lines.push(`grant select on table ${table} to anon;`);
    } else if (table === 'roles') {
      lines.push(`-- ${table} (sensitive — admin/manager read-only, anon select)`);
      lines.push(policy(`${table}_admin_all`) + '\n' + adminAll(table));
      lines.push(policy(`${table}_manager_select`) + '\n' + managerSelect(table));
      lines.push(policy(`${table}_user_select`) + '\n' + userSelect(table));
      lines.push(anonSelect(table));
      lines.push(`grant insert on table ${table} to anon;`);
      lines.push(`grant select on table ${table} to anon;`);
    } else if (table === 'permissions') {
      lines.push(`-- ${table} (sensitive — admin full, manager read-only)`);
      lines.push(policy(`${table}_admin_all`) + '\n' + adminAll(table));
      lines.push(policy(`${table}_manager_select`) + '\n' + managerSelect(table));
    } else if (table === 'audit_logs' || table === 'config_history') {
      lines.push(`-- ${table} (sensitive — admin read only)`);
      lines.push(policy(`${table}_admin_select`) + '\n' + adminSelect(table));
    } else if (table === 'settings' || table === 'env_vars') {
      lines.push(`-- ${table} (sensitive — admin/manager full)`);
      lines.push(policy(`${table}_admin_all`) + '\n' + adminAll(table));
      lines.push(policy(`${table}_manager_all`) + '\n' + managerAll(table));
    } else if (table === 'schema_meta') {
      lines.push(`-- ${table} (admin/manager read, anon read for version check)`);
      lines.push(policy(`${table}_admin_all`) + '\n' + adminAll(table));
      lines.push(policy(`${table}_manager_select`) + '\n' + managerSelect(table));
      lines.push(anonSelect(table));
    } else if (table === 'user_role_registry') {
      lines.push(`-- ${table} (admin only — lookup via security-definer function)`);
      lines.push(policy(`${table}_admin_all`) + '\n' + adminAll(table));
    } else if (kind === 'system') {
      lines.push(`-- ${table} (system — admin full, manager/user select, anon select)`);
      lines.push(policy(`${table}_admin_all`) + '\n' + adminAll(table));
      lines.push(policy(`${table}_manager_select`) + '\n' + managerSelect(table));
      lines.push(policy(`${table}_user_select`) + '\n' + userSelect(table));
      lines.push(anonSelect(table));
    } else {
      lines.push(`-- ${table} (standard — admin/manager full, user read)`);
      lines.push(policy(`${table}_admin_all`) + '\n' + adminAll(table));
      lines.push(policy(`${table}_manager_all`) + '\n' + managerAll(table));
      lines.push(policy(`${table}_user_select`) + '\n' + userSelect(table));
    }
    lines.push('');
  }

  return lines.join('\n');
}

function systemSqlGrants() {
  return [
    '-- ============================================================',
    '-- 13. SUPABASE-STYLE GRANTS (authenticated must have table access for RLS to apply)',
    '-- ============================================================',
    '-- Standard Supabase pattern: GRANT ON ALL TABLES + RLS on every table.',
    '-- The blanket grant allows authenticated users to *reach* the RLS check;',
    '-- RLS policies on every table filter what each role can actually do.',
    '-- Without this grant, RLS policies are never evaluated.',
    '--',
    '-- For non-Supabase providers (MySQL, SQLite, etc.), the adapter layer should',
    '-- replace this with targeted per-tier grants (public read, internal CRUD,',
    '-- restricted admin-only) at the adapter level — not in the SQL schema.',
    "do $$ begin if exists (select 1 from pg_roles where rolname = 'authenticated') then",
    '  grant usage on schema public to authenticated;',
    '  grant select, insert, update, delete on all tables in schema public to authenticated;',
    '  grant usage on all sequences in schema public to authenticated;',
    '  alter default privileges in schema public grant select, insert, update, delete on tables to authenticated;',
    '  alter default privileges in schema public grant usage on sequences to authenticated;',
    'end if; end $$;',
    '',
    "do $$ begin if exists (select 1 from pg_roles where rolname = 'anon') then",
    '  grant usage on schema public to anon;',
    '  grant select on all tables in schema public to anon;',
    '  alter default privileges in schema public grant select on tables to anon;',
    'end if; end $$;',
    '',
    '-- Function-level grants for system functions',
    "do $$ begin if exists (select 1 from pg_roles where rolname = 'authenticated') then",
    "  grant execute on function exec_sql(text) to authenticated; end if; end $$;",
    "do $$ begin if exists (select 1 from pg_roles where rolname = 'anon') then",
    "  grant execute on function exec_sql(text) to anon; end if; end $$;",
    "do $$ begin if exists (select 1 from pg_roles where rolname = 'service_role') then",
    "  grant execute on function exec_sql(text) to service_role; end if; end $$;",
    "do $$ begin if exists (select 1 from pg_roles where rolname = 'authenticated') then",
    "  grant execute on function safe_ddl(text) to authenticated; end if; end $$;",
    "do $$ begin if exists (select 1 from pg_roles where rolname = 'anon') then",
    "  grant execute on function safe_ddl(text) to anon; end if; end $$;",
    "do $$ begin if exists (select 1 from pg_roles where rolname = 'service_role') then",
    "  grant execute on function safe_ddl(text) to service_role; end if; end $$;",
    "do $$ begin if exists (select 1 from pg_roles where rolname = 'anon') then",
    "  grant execute on function next_lx_id(text) to anon; end if; end $$;",
  ].join('\n');
}

function systemSqlIndexes() {
  return [
    '-- ============================================================',
    '-- 14. INDEXES',
    '-- ============================================================',
    'create index if not exists idx_schema_registry_version on "schema_registry" ("version");',
    'create index if not exists idx_field_registry_entity on "field_registry" ("entity");',
    'create index if not exists idx_provider_registry_active on "provider_registry" ("active");',
    'create index if not exists idx_provider_adapter_active on "provider_adapter_registry" ("active");',
    'create index if not exists idx_schema_mapping_active on "schema_mapping" ("active");',
    'create index if not exists idx_mapping_history_entity_name on "mapping_history" ("entity_name");',
    'create index if not exists idx_provider_capabilities_provider on "provider_capabilities" ("provider");',
    'create index if not exists idx_provider_capabilities_feature on "provider_capabilities" ("feature");',
    'create index if not exists idx_entity_prefix_registry_prefix on "entity_prefix_registry" ("prefix");',
    'create index if not exists idx_foreign_key_registry_from_entity on "foreign_key_registry" ("from_entity");',
    'create index if not exists idx_foreign_key_registry_to_entity on "foreign_key_registry" ("to_entity");',
  ].join('\n');
}

function systemSqlSchemaVersion() {
  const version = SCHEMA_VERSION;
  return [
    '-- ============================================================',
    '-- 15. SCHEMA VERSION STAMP (P3 — fixed: excluded.version)',
    '-- ============================================================',
    `insert into schema_registry (id, version, description, applied_at)`,
    `values ('schema_version', ${version}, 'Schema v${version} — system infrastructure', now())`,
    "on conflict (id) do update set version = excluded.version, description = excluded.description, applied_at = now();",
  ].join('\n');
}



const COMPILERS = { supabase: toSupabase, firebase: toFirebase, mongodb: toMongo, local: toLocal };

export const SchemaCompiler = {
  compile(provider, schemaOrName) {
    const schema = typeof schemaOrName === 'string' ? getSchema(schemaOrName) : schemaOrName;
    if (!schema) throw new Error(`Unknown schema: ${schemaOrName}`);
    const fn = COMPILERS[provider] || COMPILERS.local;
    return fn(schema);
  },

  compileAll(provider, onlyCollections) {
    const schemas = onlyCollections
      ? listSchemas().filter((s) => onlyCollections.includes(s.collection))
      : listSchemas();
    return schemas.map((s) => this.compile(provider, s));
  },

  installArtifact(provider, { onlyCollections, present, missing } = {}) {
    const parts = this.compileAll(provider, onlyCollections);
    if (provider === 'supabase') {
      const preDdl = this.systemSqlSections();
      const header = present || missing ? [
        '-- ============================================================',
        '-- LEXAI SCHEMA INSTALLATION SQL',
        '-- ============================================================',
        present?.length > 0 ? `-- Existing tables: ${present.join(', ')}` : '-- No existing tables found — generating full schema.',
        missing?.length > 0 ? `-- New tables to create: ${missing.join(', ')}` : '-- All tables will be created.',
        missing?.length === 0 && present?.length > 0 ? '-- All required tables already exist. Only system SQL will run.' : '',
        '--',
        '-- NOTE: System infrastructure (registry tables, functions, policies)',
        '-- uses IF NOT EXISTS / CREATE OR REPLACE and runs unconditionally.',
        '-- ============================================================',
        '',
      ].filter(Boolean).join('\n') : '';
      const ddl = parts.map((p) => p.sql).join('\n\n');
      const postDdl = this.systemSqlPostDdl({ onlyCollections, present, missing });
      const text = [preDdl, header, ddl, postDdl].filter(Boolean).join('\n\n');
      return { kind: 'sql', schemaVersion: SCHEMA_VERSION, text };
    }
    if (provider === 'firebase') {
      return {
        kind: 'firebase',
        schemaVersion: SCHEMA_VERSION,
        rules: `rules_version = '2';\nservice cloud.firestore {\n  match /databases/{database}/documents {\n${parts.map((p) => p.rules).join('\n')}\n  }\n}`,
        indexes: { indexes: parts.flatMap((p) => p.indexes) },
      };
    }
    if (provider === 'mongodb') {
      return {
        kind: 'mongodb',
        schemaVersion: SCHEMA_VERSION,
        mongoose: parts.map((p) => p.mongooseDefinition).join('\n\n'),
        validators: Object.fromEntries(parts.map((p) => [p.collection, p.jsonSchema])),
        indexes: Object.fromEntries(parts.map((p) => [p.collection, p.indexes])),
      };
    }
    return { kind: 'local', schemaVersion: SCHEMA_VERSION, collections: parts.map((p) => p.init) };
  },

  // P1: System SQL emitted in correct dependency order
  // P4: FK creation emitted AFTER all application DDL
  systemSqlSections() {
    const sections = [
      systemSqlMigrationRegistry(),
      systemSqlExecSql(),
      systemSqlSafeDdl(),
      systemSqlSafeCreateFk(),
      systemSqlResolveEntity(),
      systemSqlRegistryTables(),
      systemSqlMappingTables(),
      systemSqlProviderTables(),
      systemSqlIdEngine(),
      systemSqlSupabaseAuth(),
      systemSqlUserRoleRegistry(),
      systemSqlVerifyInstallation(),
    ];
    return sections.join('\n\n');
  },

  // P4: FK + RLS + Policies + Grants + Indexes + triggers (emitted after application DDL)
  systemSqlPostDdl({ onlyCollections, present, missing } = {}) {
    return [
      systemSqlForeignKeys({ onlyCollections }),
      systemSqlRls({ onlyCollections }),
      systemSqlPolicies({ onlyCollections }),
      systemSqlUserRoleTrigger(),
      systemSqlGrants({ onlyCollections }),
      systemSqlIndexes({ onlyCollections }),
      systemSqlSchemaVersion(),
    ].join('\n\n');
  },
};

export default SchemaCompiler;
