// SchemaCompiler — turns the universal schema descriptors into provider-specific
// artifacts. This is the SINGLE SOURCE OF TRUTH for "what a table/collection looks
// like" on each backend; no schema shape is duplicated anywhere else (the
// migration strategies and the installer both consume this).
//
// It imports NO database SDK and runs in the browser: it EMITS artifacts (SQL
// text, rule strings, mongoose-definition source, index specs). Executing those
// artifacts is the installer's job, using each provider's browser-reachable API.
import { listSchemas, getSchema, SCHEMA_VERSION } from './index.js';

// ---- type maps ------------------------------------------------------------
const PG = { string: 'text', number: 'numeric', boolean: 'boolean', datetime: 'timestamptz', array: 'jsonb', object: 'jsonb', json: 'jsonb' };
const MONGOOSE = { string: 'String', number: 'Number', boolean: 'Boolean', datetime: 'Date', array: 'Array', object: 'Object', json: 'Object' };
const BSON = { string: 'string', number: 'number', boolean: 'bool', datetime: 'date', array: 'array', object: 'object', json: 'object' };
const FS = { string: 'string', number: 'number', boolean: 'bool', datetime: 'timestamp', array: 'list', object: 'map', json: 'map' };

const q = (id) => `"${id}"`;

// ---- Supabase / Postgres --------------------------------------------------
function toSupabase(schema) {
  const cols = Object.entries(schema.fields).map(([name, type]) => {
    if (name === schema.primaryKey) return `  ${q(name)} text primary key`;
    return `  ${q(name)} ${PG[type] || 'text'}`;
  });
  const createTable = `create table if not exists ${q(schema.collection)} (\n${cols.join(',\n')}\n);`;
  const createIndexes = (schema.indexes || []).map(
    (f) => `create index if not exists ${`idx_${schema.collection}_${f}`} on ${q(schema.collection)} (${q(f)});`
  );
  // Additive column diff against columns that already exist on the backend.
  const alterTable = (existingColumns = []) =>
    Object.entries(schema.fields)
      .filter(([name]) => !existingColumns.includes(name))
      .map(([name, type]) => `alter table ${q(schema.collection)} add column if not exists ${q(name)} ${name === schema.primaryKey ? 'text' : (PG[type] || 'text')};`);
  return { provider: 'supabase', collection: schema.collection, createTable, createIndexes, alterTable, sql: [createTable, ...createIndexes].join('\n') };
}

// ---- Firebase / Firestore -------------------------------------------------
function toFirebase(schema) {
  // Firestore is schemaless; we emit a validation-rule block and index defs.
  const checks = Object.entries(schema.fields)
    .filter(([name]) => name !== schema.primaryKey)
    .map(([name, type]) => {
      const t = FS[type] || 'string';
      const present = `(!('${name}' in request.resource.data) || request.resource.data.${name} == null || request.resource.data.${name} is ${t})`;
      return `        ${present}`;
    });
  const required = (schema.required || []).map((f) => `        '${f}' in request.resource.data`);
  const rule = [
    `    match /${schema.collection}/{docId} {`,
    '      allow read: if true;',
    '      allow write: if',
    [...required, ...checks].join(' &&\n') || '        true',
    '      ;',
    '    }',
  ].join('\n');
  const indexes = (schema.indexes || []).map((f) => ({
    collectionGroup: schema.collection,
    queryScope: 'COLLECTION',
    fields: [{ fieldPath: f, order: 'ASCENDING' }],
  }));
  return {
    provider: 'firebase',
    collection: schema.collection,
    definition: { collection: schema.collection, fields: schema.fields, required: schema.required || [] },
    rules: rule,
    indexes,
  };
}

// ---- MongoDB --------------------------------------------------------------
function toMongo(schema) {
  // mongoose is Node-only — we emit DEFINITION SOURCE (a string) plus a portable
  // $jsonSchema validator and index specs the Atlas Data API/back-end can apply.
  const defLines = Object.entries(schema.fields).map(([name, type]) => {
    const mt = MONGOOSE[type] || 'String';
    const idx = (schema.indexes || []).includes(name) ? ', index: true' : '';
    const uniq = name === schema.primaryKey ? ', unique: true' : '';
    return `  ${name}: { type: ${mt}${idx}${uniq} }`;
  });
  const mongooseDefinition =
    `// generated by SchemaCompiler — collection: ${schema.collection}\n` +
    `const ${schema.collection}Schema = new mongoose.Schema({\n${defLines.join(',\n')}\n}, { collection: '${schema.collection}', strict: false });`;

  const properties = {};
  Object.entries(schema.fields).forEach(([name, type]) => { properties[name] = { bsonType: BSON[type] || 'string' }; });
  const jsonSchema = {
    $jsonSchema: {
      bsonType: 'object',
      required: schema.required || [],
      properties,
    },
  };
  const indexes = [
    { key: { [schema.primaryKey]: 1 }, name: `${schema.primaryKey}_unique`, unique: true },
    ...(schema.indexes || []).map((f) => ({ key: { [f]: 1 }, name: `${f}_idx` })),
  ];
  return { provider: 'mongodb', collection: schema.collection, mongooseDefinition, jsonSchema, indexes };
}

// ---- Local ----------------------------------------------------------------
function toLocal(schema) {
  return {
    provider: 'local',
    collection: schema.collection,
    init: { collection: schema.collection, fields: Object.keys(schema.fields), defaults: schema.defaults || {} },
  };
}

const COMPILERS = { supabase: toSupabase, firebase: toFirebase, mongodb: toMongo, local: toLocal };

export const SchemaCompiler = {
  // Compile one schema (by name or descriptor) for a provider.
  compile(provider, schemaOrName) {
    const schema = typeof schemaOrName === 'string' ? getSchema(schemaOrName) : schemaOrName;
    if (!schema) throw new Error(`Unknown schema: ${schemaOrName}`);
    const fn = COMPILERS[provider] || COMPILERS.local;
    return fn(schema);
  },

  // Compile every schema for a provider.
  compileAll(provider) {
    return listSchemas().map((s) => this.compile(provider, s));
  },

  // A single install script/bundle for a provider.
  installArtifact(provider) {
    const parts = this.compileAll(provider);
    if (provider === 'supabase') {
      return { kind: 'sql', schemaVersion: SCHEMA_VERSION, text: parts.map((p) => p.sql).join('\n\n') };
    }
    if (provider === 'firebase') {
      return {
        kind: 'firebase',
        schemaVersion: SCHEMA_VERSION,
        rules: `rules_version = '2';\nservice cloud.firestore {\n  match /databases/{database}/documents {\n${parts.map((p) => p.rules).join('\n')}\n  }\n}`,
        indexes: { indexes: parts.flatMap((p) => p.indexes) },
      };
    }
    if (provider === 'mongodb') {
      return {
        kind: 'mongodb',
        schemaVersion: SCHEMA_VERSION,
        mongoose: parts.map((p) => p.mongooseDefinition).join('\n\n'),
        validators: Object.fromEntries(parts.map((p) => [p.collection, p.jsonSchema])),
        indexes: Object.fromEntries(parts.map((p) => [p.collection, p.indexes])),
      };
    }
    return { kind: 'local', schemaVersion: SCHEMA_VERSION, collections: parts.map((p) => p.init) };
  },
};

export default SchemaCompiler;
