// Universal schema — tasks (standalone task / to-do management module).
export const TasksSchema = {
  collection: 'tasks',
  label: 'Tasks',
  primaryKey: 'id',
  core: false,
  fields: {
    id: 'string',
    title: 'string',
    description: 'string',
    notes: 'string',
    category: 'string',
    priority: 'string',
    status: 'string',
    active: 'boolean',
    due_date: 'datetime',
    due_time: 'string',
    start_date: 'datetime',
    end_date: 'datetime',
    reminder: 'boolean',
    reminder_time: 'string',
    color: 'string',
    case_id: 'string',
    hearing_id: 'string',
    tags: 'string',
    attachments: 'string',
    created_by: 'string',
    archived: 'boolean',
    created_at: 'datetime',
    updated_at: 'datetime',
  },
  required: ['title'],
  defaults: {
    description: '',
    notes: '',
    category: '',
    priority: 'Medium',
    status: 'Pending',
    active: true,
    reminder: false,
    color: '#6b7280',
    tags: '',
    attachments: '',
    archived: false,
    created_by: '',
  },
  indexes: ['category', 'priority', 'status', 'due_date', 'active', 'archived', 'case_id', 'hearing_id'],
};

export default TasksSchema;
